= Κανονισμός για τη Διασφάλιση του Απορρήτου των Ηλεκτρονικών Επικοινωνιών
:docnumber: 304/2025
:doctype: ap
:language: el
:mn-document-class: lawgr
:mn-output-extensions: xml,html
:copyright-year: 2025
:published-date: 2025-08-07
:script: Grek
:fek-number: 4268
:fek-series: Β'
:fek-year: 2025
:publisher: ΑΡΧΗ ΔΙΑΣΦΑΛΙΣΗΣ ΤΟΥ ΑΠΟΡΡΗΤΟΥ ΤΩΝ ΕΠΙΚΟΙΝΩΝΙΩΝ
// Uncomment for hierarchical paragraph numbering (e.g. 3.1, 3.2):
:inheritnumbering: true
:toc:
:toclevels: 6

[.preface]
== {empty}

[align=center]
ΑΠΟΦΑΣΗ Αριθμ. 304/2025 +
*Κανονισμός για τη Διασφάλιση του Απορρήτου των Ηλεκτρονικών Επικοινωνιών*

[align=center]
*Η ΑΡΧΗ ΔΙΑΣΦΑΛΙΣΗΣ ΤΟΥ ΑΠΟΡΡΗΤΟΥ ΤΩΝ ΕΠΙΚΟΙΝΩΝΙΩΝ (ΑΔΑΕ)* +
(Συνεδρίαση της 30ης Ιουλίου 2025)

*Έχοντας υπόψη:*

[arabic]
. Τις διατάξεις:
.. Του ν. 3115/2003 «Αρχή διασφάλισης του Απορρήτου των Επικοινωνιών» (Α’ 47), ιδίως τη διάταξη της παρ. 1 του άρθρου 6 αυτού,
.. του ν. 5160/2024 «Ενσωμάτωση της Οδηγίας (ΕΕ) 2022/2555 του Ευρωπαϊκού Κοινοβουλίου και του Συμβουλίου, της 14ης Δεκεμβρίου 2022, σχετικά με μέτρα για υψηλό κοινό επίπεδο κυβερνοασφάλειας σε ολόκληρη την Ένωση, την τροποποίηση του Κανονισμού (ΕΕ) 910/2014 και της Οδηγίας (ΕΕ) 2018/1972, και την κατάργηση της Οδηγίας (ΕΕ) 2016/1148 (Οδηγία NIS 2) και άλλες διατάξεις», ιδίως των άρθρων 31 και 32 αυτού,
.. του ν. 3674/2008 «Ενίσχυση του θεσμικού πλαισίου διασφάλισης του απορρήτου της τηλεφωνικής επικοινωνίας και άλλες διατάξεις» (Α’ 136), ιδίως της παρ. 4 του άρθρου 4 και του άρθρου 5 αυτού,.
.. του ν. 3959/2011 «Προστασία του ελεύθερου ανταγωνισμού» (Α’ 93),
.. του ν. 3471/2006 «Προστασία δεδομένων προσωπικού χαρακτήρα και της ιδιωτικής ζωής στον τομέα των ηλεκτρονικών επικοινωνιών και τροποποίηση του ν. 2472/1997» (Α’ 133),
.. της υπ’ αρ. 165/2011 απόφασης της ΑΔΑΕ «Κανονισμός για τη Διασφάλιση του Απορρήτου των Ηλεκτρονικών Επικοινωνιών» (Β’ 2715),
.. της υπ’ αρ. 205/2013 απόφασης της ΑΔΑΕ «Κανονισμός για την Ασφάλεια και την Ακεραιότητα Δικτύων και Υπηρεσιών Ηλεκτρονικών Επικοινωνιών» (Β’ 1742),
.. της υπ’ αρ. 28/2024 απόφασης της ΑΔΑΕ «Κανονισμός για την Ασφάλεια Δικτύων και Υπηρεσιών Ηλεκτρονικών Επικοινωνιών» (Β’ 551),
.. της υπ’ αρ. 991/4/2021 (Β’ 2265) απόφασης της ΕΕΤΤ (Κανονισμός Γενικών Αδειών).
. Την υπ’ αρ. 58347οικ/21.12.2020 απόφαση του Υπουργού Δικαιοσύνης (Υ.Ο.Δ.Δ. 1066), περί διορισμού νέων μελών στην Αρχή Διασφάλισης του Απορρήτου των Επικοινωνιών.
. Τις υπ’ αρ. 48024οικ/28.09.2023 και 48025οικ./28.09.2023 (Υ.Ο.Δ.Δ. 1039) αποφάσεις του Υπουργού Δικαιοσύνης περί διορισμού Αντιπροέδρου, Αναπληρωτή Αντιπροέδρου και νέων μελών στην Ολομέλεια της Α.Δ.Α.Ε.
. Την παρ. 2 του άρθρου 3 του ν. 3051/2002.
. Την υπ’ αρ. 198/2025 εισήγηση προς την Ολομέλεια της Α.Δ.Α.Ε.
. Τα πρακτικά των από 19 Μαρτίου 2025, 4 Ιουνίου 2025, 18 Ιουνίου 2025 και 30 Ιουλίου 2025 συνεδριάσεων της Ολομέλειας της Α.Δ.Α.Ε.
. Το γεγονός ότι από τις διατάξεις της παρούσας αποφάσεως δεν προκαλείται δαπάνη για το τρέχον και τα επόμενα οικονομικά έτη εις βάρος του κρατικού προϋπολογισμού.
. Το γεγονός ότι οι διατάξεις της παρούσας δεν αφορούν σε διοικητική διαδικασία για την οποία υπάρχει υποχρέωση καταχώρισης στο ΕΜΔΔ-ΜΙΤΟΣ, αποφασίζει:

Την έκδοση του παρόντος Κανονισμού, οι διατάξεις του οποίου έχουν ως ακολούθως:

[heading=part,type=general-provisions]
== ΓΕΝΙΚΕΣ ΔΙΑΤΑΞΕΙΣ

[heading=article]
=== Σκοπός -- Πεδίο Εφαρμογής

[heading=paragraph]
==== {empty}

Με τον παρόντα Κανονισμό καθορίζονται τα τεχνικά και οργανωτικά μέτρα που πρέπει να λαμβάνουν όλα τα πρόσωπα που παρέχουν δημόσια δίκτυα ηλεκτρονικών επικοινωνιών ή διαθέσιμες στο κοινό υπηρεσίες ηλεκτρονικών επικοινωνιών (εφεξής καλούμενοι για λόγους συντομίας «οι πάροχοι»), για τη διασφάλιση του απορρήτου των επικοινωνιών, με την κατάλληλη διαχείριση του κινδύνου όσον αφορά στην ασφάλεια των δικτύων και υπηρεσιών τους.

[heading=paragraph]
==== {empty}

Τα μέτρα αυτά αφορούν το απόρρητο των δικτύων και των υπηρεσιών ηλεκτρονικών επικοινωνιών, καθώς και των δεδομένων που αποθηκεύονται, μεταδίδονται ή υποβάλλονται σε επεξεργασία μέσω αυτών, σύμφωνα με την κείμενη νομοθεσία.

[heading=paragraph]
==== {empty}

Οι πάροχοι υποχρεούνται να διαθέτουν και να εφαρμόζουν Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών (Networks and Services Security Policy), κατά τις διατάξεις του παρόντος, όπως ειδικότερα ορίζεται στο άρθρο 12 του παρόντος.

[heading=paragraph]
==== {empty}

Εξαιρούνται από τις διατάξεις του παρόντος οι πάροχοι που παρέχουν τις ακόλουθες κατηγορίες δικτύων ή/και υπηρεσιών ηλεκτρονικών επικοινωνιών, όπως προβλέπονται στον Κανονισμό Γενικών Αδειών της Εθνικής Επιτροπής Τηλεπικοινωνιών και Ταχυδρομείων, όπως εκάστοτε ισχύει:

. S014: Υπηρεσίες μηχανή με μηχανή (Μ2Μ)
. S015: Δορυφορική συλλογή ειδήσεων (Satellite News Gathering)
. S016: Επίγεια συλλογή ειδήσεων (ENG)
. S025: Υπηρεσίες ραδιοεπικοινωνιών, όπως τηλεματικής, τηλεμετρίας, ραδιοεντοπισμού
. N010: Δίκτυο μετάδοσης σημάτων επίγειας ψηφιακής ευρυεκπομπής, με χρήση ραδιοσυχνοτήτων για την εκπομπή τηλεοπτικού σήματος

[heading=article]
=== Ορισμοί

Για τους σκοπούς του παρόντος Κανονισμού νοούνται ως:

*«Δεδομένα Επικοινωνίας (Communication Data)»*: το περιεχόμενο και τα συναφή δεδομένα κίνησης και θέσης για κάθε επικοινωνία.

*«Περιστατικό Ασφάλειας (Security Incident)»* για τη διασφάλιση του απορρήτου των επικοινωνιών: κάθε συμβάν που αφορά στην ασφάλεια των δικτύων ή των υπηρεσιών ηλεκτρονικών επικοινωνιών και έχει αρνητική επίπτωση στο απόρρητο των επικοινωνιών ή δύναται να σχετίζεται με τη διασφάλιση του απορρήτου των επικοινωνιών, καθώς και κάθε περίπτωση παραβίασης ή ιδιαίτερου κινδύνου παραβίασης του απορρήτου των επικοινωνιών και κάθε περίπτωση μη εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών του παρόχου.

*«Πληροφοριακά και Επικοινωνιακά Συστήματα (ΠΕΣ) (Information and Communication Systems)»*: Ως ΠΕΣ νοούνται:

. Τα συστήματα (υλικό και λογισμικό, φυσικά ή εικονικά), με τα οποία πραγματοποιείται η παροχή δικτύων ή/και υπηρεσιών ηλεκτρονικών επικοινωνιών ή/και με τα οποία πραγματοποιούνται εργασίες σε δεδομένα επικοινωνίας.
. Τα συστήματα που χρησιμοποιούνται για την υποστήριξη, διαχείριση, εποπτεία, λειτουργία, έλεγχο πρόσβασης και ασφάλεια των ως άνω υπό σημείο (α) συστημάτων.
. Τα συστήματα που περιέχουν πληροφορίες που είναι απαραίτητες για την πραγματοποίηση εργασιών στα ως άνω υπό σημείο (α) συστήματα ή σε δεδομένα επικοινωνίας.

Με βάση τα ανωτέρω, στα ΠΕΣ περιλαμβάνονται, κατ`' ελάχιστον, τα μέσα μετάδοσης και διασύνδεσης, οι μεταγωγείς, οι δρομολογητές, συμπεριλαμβανομένων των δρομολογητών των συνδρομητών ή χρηστών για την πρόσβαση και τη διαχειριστική εποπτεία που ασκούν οι πάροχοι επί αυτών, τα συστήματα για την πρόσβαση στο Διαδίκτυο, τα συστήματα διαχείρισης και εποπτείας, οι εξυπηρετητές ηλεκτρονικού ταχυδρομείου, τα συστήματα για την άρση του απορρήτου των επικοινωνιών (συστήματα νόμιμης επισύνδεσης και διατήρησης δεδομένων), τα συστήματα ελέγχου φυσικής και λογικής (τοπικής και απομακρυσμένης) πρόσβασης, τα τείχη προστασίας (firewalls), τα συστήματα ανίχνευσης/αποτροπής εισβολών, τα συστήματα ανίχνευσης κακόβουλου λογισμικού και ανεπιθύμητης αλληλογραφίας, τα συστήματα καταγραφής και διατήρησης αρχείων καταγραφής, τα συστήματα χρέωσης συνδρομητών, τα συστήματα πωλήσεων και εξυπηρέτησης πελατών, τα συστήματα πρόληψης τηλεπικοινωνιακής απάτης, οι βάσεις δεδομένων που περιέχουν δεδομένα επικοινωνίας ή πληροφορίες σχετικές με την παροχή υπηρεσιών ηλεκτρονικών επικοινωνιών και τα συστήματα επεξεργασίας αυτών των δεδομένων ή πληροφοριών.

Κατά τα λοιπά, ισχύουν οι ορισμοί που περιλαμβάνονται στο άρθρο 110 του ν. 4727/2020 («Ψηφιακή διακυβέρνηση - Ηλεκτρονικές Επικοινωνίες και άλλες διατάξεις», Α'184).

[heading=part,type=substantive-provisions]
== Περιεχόμενο Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών

[heading=article]
=== Διακυβέρνηση Πολιτικής Ασφάλειας και Διαχείριση Κινδύνου

[heading=subarticle]
==== Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών

[heading=paragraph]
===== {empty}

Η Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών αφορά τους χρήστες, συνδρομητές, εργαζόμενους και συνεργάτες του παρόχου, έχει ως σκοπό τον καθορισμό και την υλοποίηση, από τον πάροχο, των κατάλληλων τεχνικών και οργανωτικών μέτρων για την επίτευξη του σκοπού της διασφάλισης του απορρήτου των επικοινωνιών και εφαρμόζεται σε όλα τα ΠΕΣ, όπως ορίζονται ανωτέρω.

[heading=paragraph]
===== {empty}

Η Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών έχει αρθρωτή δομή και αποτελείται από επιμέρους ενότητες, οι οποίες ορίζουν τις απαιτήσεις ασφάλειας που πρέπει να ικανοποιούνται για κάθε επιμέρους κατηγορία ειδικών θεμάτων.

[heading=paragraph]
===== {empty}

Σε περίπτωση που η Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών εντάσσεται σε ευρύτερη πολιτική ασφάλειας πληροφοριών και επικοινωνιών του παρόχου, αυτός διαθέτει αρχείο με αναλυτική αντιστοίχιση της δομής της ευρύτερης πολιτικής ασφάλειας πληροφοριών και επικοινωνιών με τις απαιτήσεις του παρόντος Κανονισμού, κατά άρθρο, παράγραφο και εδάφιο αυτού.
Οι πάροχοι που αναφέρονται στην παρ. 12.2 του άρθρου 12 του παρόντος, υποβάλλουν στην ΑΔΑΕ το εν λόγω αρχείο αντιστοίχισης μαζί με την υποβολή προς έγκριση της Πολιτικής τους.

[heading=paragraph]
===== {empty}

Κάθε αδυναμία συμμόρφωσης με τις απαιτήσεις που ορίζονται στον παρόντα Κανονισμό καταγράφεται και τεκμηριώνεται επαρκώς στην Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών.
Ειδικά για τις αδυναμίες συμμόρφωσης που οφείλονται σε τεχνική αδυναμία κάλυψης συγκεκριμένων απαιτήσεων, ο πάροχος καταγράφει, επιπλέον, τις προϋποθέσεις και τις ενέργειες για την κάλυψη αυτών των απαιτήσεων και άρση της αδυναμίας, καθώς και το σχετικό χρονοδιάγραμμα προς τον σκοπό αυτόν.

[heading=paragraph]
===== {empty}

Για την υλοποίηση των επιμέρους απαιτήσεων της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών, ορίζονται, τεκμηριώνονται, εφαρμόζονται και αναθεωρούνται συγκεκριμένες διαδικασίες ασφάλειας, οδηγίες εργασίας, τεχνικά και άλλα οργανωτικά εγχειρίδια.
Τα παραπάνω έγγραφα ορίζουν συγκεκριμένες ενέργειες των εργαζομένων, συνεργατών, χρηστών και συνδρομητών του παρόχου, την αλληλουχία των ενεργειών, τους υπεύθυνους για την εκτέλεσή τους και τον τρόπο και τα μέσα τεκμηρίωσής τους.

[heading=paragraph]
===== {empty}

Ο πάροχος εξετάζει περιοδικά, κατ’ ελάχιστον κάθε δύο (2) έτη ή μετά από την εκδήλωση σημαντικού περιστατικού ασφάλειας, την ανάγκη τυχόν αναθεώρησης της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών και αποφασίζει σχετικώς, λαμβάνοντας υπόψη κατ’ ελάχιστον τα αποτελέσματα της Αποτίμησης Κινδύνου, τα αποτελέσματα του εσωτερικού ελέγχου και των δοκιμών ασφάλειας στις οποίες έχει προβεί, τα περιστατικά ασφάλειας που τυχόν έχει αντιμετωπίσει, και τις επιχειρησιακές και οργανωτικές αλλαγές που τυχόν έχουν προκύψει.
Σε περίπτωση που ο πάροχος αποφασίσει ότι η Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών δεν χρειάζεται αναθεώρηση, τεκμηριώνει εγγράφως την απόφαση αυτή, ενώ, σε περίπτωση που ο πάροχος της παρ. 12.2 του άρθρου 12 του παρόντος προβεί σε αναθεώρηση της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών, την υποβάλλει προς έγκριση στην ΑΔΑΕ.

[heading=subarticle]
==== Διαχείριση Κινδύνου (Risk Management)

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί και εφαρμόζει Διαδικασία Αποτίμησης Κινδύνου (Risk Assessment) σχετικά με την ασφάλεια δικτύων και υπηρεσιών, βασισμένη σε μεθοδολογία που λαμβάνει υπόψη διεθνείς πρακτικές, με σκοπό την αναγνώριση, την αξιολόγηση και αντιμετώπιση των απειλών (threats) στην ασφάλεια των δικτύων και υπηρεσιών του που δύνανται να σχετίζονται με τη διασφάλιση του απορρήτου των επικοινωνιών.

[heading=paragraph]
===== {empty}

Ο πάροχος αναγνωρίζει και εξετάζει ενδογενείς και εξωγενείς απειλές, όπως, ενδεικτικά αποτελούν οι αστοχίες υλικού και λογισμικού, η πλημμελής εφαρμογή της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών και των συναφών διαδικασιών, οι πράξεις ή παραλείψεις εργαζομένων και συνεργατών, οι απειλές προερχόμενες από άλλα διασυνδεδεμένα δίκτυα, οι κακόβουλες ενέργειες και οι πράξεις δολιοφθοράς, τα ατυχήματα και τα φυσικά φαινόμενα.

[heading=paragraph]
===== {empty}

Η Αποτίμηση Κινδύνου περιλαμβάνει κατ' ελάχιστον τα παρακάτω:

[heading=paragraph]
====== {empty}

Ο πάροχος καταρτίζει και διατηρεί κατάλογο των πόρων του (ΠΕΣ, εγκαταστάσεις, διαδικασίες, προσωπικό), με συνοπτική περιγραφή τους.

[heading=paragraph]
====== {empty}

Ο πάροχος καταρτίζει και διατηρεί κατάλογο με τις διαφορετικές εκτιμώμενες απειλές που μπορούν να εκδηλωθούν σε πόρους του, καθώς και τις ευπάθειες (vulnerabilities), τα ευάλωτα σημεία και τις αδυναμίες των πόρων του.
Επιπρόσθετα, ταξινομεί τους πόρους του ως προς την κρισιμότητά τους, λαμβάνοντας υπόψη τις απειλές που μπορεί να τους επηρεάσουν.

[heading=paragraph]
====== {empty}

Ο πάροχος πραγματοποιεί αξιολόγηση επικινδυνότητας (risk evaluation), ήτοι αξιολογεί την πιθανότητα πραγματοποίησης των απειλών που έχει αναγνωρίσει και εκτιμά την επίδρασή τους στην ασφάλεια των δικτύων και υπηρεσιών του.

[heading=paragraph]
====== {empty}

Ο πάροχος καθορίζει τα κατάλληλα μέτρα ασφάλειας για την αντιμετώπισή των απειλών, συμπληρωματικά ως προς τα μέτρα ασφάλειας που ορίζονται από τον παρόντα Κανονισμό, το χρονοδιάγραμμα υλοποίησης αυτών, καθώς και διαδικασίες αξιολόγησης της αποτελεσματικότητας των επιλεγέντων μέτρων.

[heading=paragraph]
===== {empty}

Η Αποτίμηση Κινδύνου πραγματοποιείται από τον πάροχο πριν τη σύνταξη της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών και εφεξής, κατ’ ελάχιστον κάθε δύο (2) έτη ή μετά από την εκδήλωση σημαντικού περιστατικού ασφαλείας
Για την αναθεώρηση της Αποτίμησης Κινδύνου λαμβάνονται υπόψη:

. η αποτελεσματικότητα των εφαρμοζόμενων μέτρων,
. η αναγνώριση νέων απειλών,
. η καταγραφή νέων ευπαθειών των ΠΕΣ,
. οργανωτικές ή τεχνολογικές αλλαγές,
. αλλαγές στο νομοθετικό πλαίσιο, σε εθνικό ή κοινοτικό επίπεδο,
. τα αποτελέσματα των ελέγχων που πραγματοποιούνται από τις Ελεγκτικές Αρχές και τις σχετικές υποδείξεις τους και
. κάθε άλλο νέο στοιχείο που πρέπει να λάβει υπόψη του ο πάροχος.

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί καταγεγραμμένη την περιγραφή της εφαρμοσθείσας μεθοδολογίας Αποτίμησης Κινδύνου, καθώς και τα αποτελέσματα της Αποτίμησης Κινδύνου (τα στοιχεία της παρ. 3.2.3 του παρόντος άρθρου).
Όλα τα ανωτέρω είναι διαθέσιμα κατά τον τακτικό ή έκτακτο έλεγχο της εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών από την ΑΔΑΕ.

[heading=subarticle]
==== Ρόλοι και Αρμοδιότητες

[heading=paragraph]
===== {empty}

Ο πάροχος ορίζει, στην Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών, τις διοικητικές οντότητες και τα φυσικά πρόσωπα στα οποία ανατίθενται συγκεκριμένες αρμοδιότητες σχετικά με τη διαχείριση και εφαρμογή της Πολιτικής.
Ο πάροχος αναθέτει τους ρόλους και τις αρμοδιότητες στους εργαζόμενους ή συνεργάτες του, και διατηρεί σχετικό αρχείο με τις εν λόγω αναθέσεις.

[heading=paragraph]
===== {empty}

Ο πάροχος ορίζει συγκεκριμένο εργαζόμενό του, ως Υπεύθυνο Ασφάλειας Δικτύων και Υπηρεσιών, επιφορτισμένο με την ευθύνη ελέγχου της υλοποίησης των μέτρων και των απαιτήσεων που ορίζονται στην Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών.
Οι πάροχοι που λειτουργούν υπό καθεστώς Γενικής Άδειας, όπως αυτό καθορίζεται από την εκάστοτε ισχύουσα νομοθεσία, κοινοποιούν στην ΑΔΑΕ τα στοιχεία του εκάστοτε Υπεύθυνου Ασφάλειας Δικτύων και Υπηρεσιών (ονοματεπώνυμο, ΑΔΤ, διεύθυνση, τηλέφωνο επικοινωνίας, διεύθυνση ηλεκτρονικού ταχυδρομείου), ιδιαιτέρως δε κατά την υποβολή της υπεύθυνης δήλωσης της παρ. 11.1 του άρθρου 11 του παρόντος Κανονισμού καθώς και σε κάθε μεταβολή αυτού.

[heading=paragraph]
===== {empty}

Ο πάροχος επανεξετάζει περιοδικά, κατ’ ελάχιστον κάθε δύο (2) έτη, τις αναθέσεις ρόλων και αρμοδιοτήτων, σύμφωνα με τους όρους και τις προϋποθέσεις της παρ. 3.1.6 του παρόντος άρθρου, και διατηρεί εγγράφως τη σχετική τεκμηρίωση.

[heading=subarticle]
==== Υποχρεώσεις Παρόχου σχετικά με τους Συνεργάτες

[heading=paragraph]
===== {empty}

Ο πάροχος ευθύνεται για το σύνολο των πράξεων οποιουδήποτε συνεργάτη, φυσικού ή νομικού προσώπου, τους οποίους χρησιμοποιεί στο πλαίσιο της παροχής των δικτύων και υπηρεσιών ηλεκτρονικών επικοινωνιών του.

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί ενημερωμένο αρχείο στο οποίο καταγράφονται οι συνεργάτες του, φυσικά ή νομικά πρόσωπα, τους οποίους χρησιμοποιεί στο πλαίσιο της παροχής των δικτύων και υπηρεσιών ηλεκτρονικών επικοινωνιών.
Σε ειδικό πεδίο του αρχείου της παρούσας παραγράφου καταγράφονται εκείνοι οι συνεργάτες που, προκειμένου να παράσχουν τις υπηρεσίες τους, αποκτούν ή δύνανται να αποκτήσουν πρόσβαση σε δεδομένα επικοινωνίας των συνδρομητών ή χρηστών των παρεχόμενων δικτύων ή υπηρεσιών, καθώς και οι συνεργάτες που κατέχουν ή διαχειρίζονται ΠΕΣ μέσω των οποίων πραγματοποιείται, αποκλειστικά ή εν μέρει, η παροχή των υπηρεσιών του παρόχου.

[heading=paragraph]
===== {empty}

Ο πάροχος συνάπτει με τους συνεργάτες της προηγούμενης παραγράφου, συμβάσεις, των οποίων το ελάχιστο περιεχόμενο περιλαμβάνει:

[heading=paragraph]
====== {empty}

Όρους εμπιστευτικότητας, μη αποκάλυψης και τήρησης του απορρήτου.

[heading=paragraph]
====== {empty}

Απαιτήσεις και μέτρα ασφάλειας που λαμβάνονται για την ασφάλεια των δικτύων και υπηρεσιών του, και επιπρόσθετα, ειδικότερα, μέτρα με τα οποία διασφαλίζεται η εμπιστευτικότητα και ακεραιότητα των δεδομένων επικοινωνίας κατά την επεξεργασία αυτών από τους συνεργάτες του παρόχου, καθώς και η οριστική διαγραφή και καταστροφή αυτών μετά τη λήξη της συνεργασίας.

[heading=paragraph]
====== {empty}

Αποδοχή εκ μέρους των συνεργατών της υποχρέωσης για τήρηση των μέτρων ασφάλειας, που αναφέρονται στην παρ. 3.4.3.2 του παρόντος άρθρου.

[heading=paragraph]
====== {empty}

Στην περίπτωση που οι συνεργάτες χρησιμοποιούν τρίτα πρόσωπα προκειμένου να παρέχουν τις υπηρεσίες τους στον πάροχο, τότε στις συμβάσεις τους με τον πάροχο περιλαμβάνεται όρος που προβλέπει την εν λόγω δυνατότητα και ο πάροχος εγκρίνει τα εν λόγω τρίτα πρόσωπα.
Οι απαιτήσεις της παρ. 3.4.3 που αφορούν στις συμβάσεις παρόχου - συνεργάτη, δεσμεύουν και τα τρίτα πρόσωπα που χρησιμοποιεί ο συνεργάτης.

[heading=paragraph]
===== {empty}

Στην περίπτωση κατά την οποία οι συνεργάτες της παρ. 3.4.2 του παρόντος άρθρου κατέχουν ή διαχειρίζονται ΠΕΣ μέσω των οποίων πραγματοποιείται, αποκλειστικά ή εν μέρει, η παροχή των υπηρεσιών του παρόχου, τότε ο πάροχος εξασφαλίζει ότι οι εν λόγω συνεργάτες συμμορφώνονται με το σύνολο των απαιτήσεων του παρόντος Κανονισμού.

[heading=paragraph]
===== {empty}

Ο πάροχος ενεργοποιεί τη Διαδικασία Δια­χείρισης Περιστατικών Ασφάλειας, σύμφωνα με την ενότητα 7.1 του άρθρου 7 του παρόντος Κανονισμού, για κάθε παραβίαση των συμβατικών όρων που αναφέρονται στην παρ. 3.4.3 του παρόντος άρθρου.

[heading=article]
=== Μέτρα σχετικά με τους Εργαζόμενους και τους Συνεργάτες

[heading=subarticle]
==== Εκπαίδευση και Ενημέρωση

[heading=paragraph]
===== {empty}

Ο πάροχος ενημερώνει και εκπαιδεύει τους εργαζόμενους και συνεργάτες του ως προς την εφαρμογή της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών και επισημαίνει τους κινδύνους που ελλοχεύουν από τυχόν παραβίασή της.

[heading=paragraph]
===== {empty}

Η ενημέρωση και η εκπαίδευση των εργαζόμενων και συνεργατών διενεργείται σε τακτά χρονικά διαστήματα, κατ’ ελάχιστον μία φορά τον χρόνο, με σκοπό την προσήκουσα επιμόρφωσή τους.

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί αρχείο εκπαιδεύσεων στο οποίο αναγράφονται κατ’ ελάχιστον αναλυτικά ο χρόνος και η διάρκεια εκπαίδευσης, το εκπαιδευτικό υλικό, τα στοιχεία των εκπαιδευτών και η αξιολόγηση κάθε εκπαιδευόμενου.

[heading=paragraph]
===== {empty}

Σε περίπτωση τροποποίησης της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών ή των διαδικασιών, τεχνικών οδηγιών ή άλλων δευτερογενών εγγράφων που σχετίζονται με την υλοποίησή της, ο πάροχος προβαίνει αμελλητί σε ενημέρωση των εργαζόμενων και συνεργατών του και διατηρεί εγγράφως τη σχετική τεκμηρίωση πραγματοποίησης της ενημέρωσης.

[heading=subarticle]
==== Διαχείριση Μεταβολών Εργαζομένων και Συνεργατών

[heading=paragraph]
===== {empty}

Σε περίπτωση πρόσληψης ή μεταβολής των καθηκόντων εργαζόμενου ή συνεργάτη, ο πάροχος προβαίνει στην ενημέρωση και εκπαίδευσή του ως προς την εφαρμογή της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών.

[heading=paragraph]
===== {empty}

Σε περίπτωση μεταβολής των καθηκόντων ή αποχώρησης εργαζόμενου ή συνεργάτη, ο πάροχος προβαίνει αμελλητί στην αντίστοιχη τροποποίηση τυχόν δικαιωμάτων που του έχουν αποδοθεί λόγω της φύσης της εργασίας του σύμφωνα με τις απαιτήσεις της εφαρμοζόμενης Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών (πχ. κάρτα εισόδου σε εγκατάσταση, πρόσβαση σε συστήματα ή δεδομένα κ.λπ.).

[heading=subarticle]
==== Υποχρεώσεις Εργαζομένων και Συνεργατών

[heading=paragraph]
===== {empty}

Οι εργαζόμενοι και συνεργάτες του παρόχου οφείλουν να συμμορφώνονται με την Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών, συμπεριλαμβανομένων των σχετικών διαδικασιών, μέτρων ασφάλειας και οδηγιών.
Για τον σκοπό αυτό, ο πάροχος καταγράφει στην Πολιτική τον τρόπο με τον οποίο εξασφαλίζει ότι οι εργαζόμενοι και συνεργάτες του λαμβάνουν γνώση και έχουν αποδεχτεί την Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών ως προς την εργασία τους, προ της απόκτησης πρόσβασης σε ΠΕΣ και σε δεδομένα επικοινωνίας.

[heading=paragraph]
===== {empty}

Οι εργαζόμενοι και συνεργάτες του παρόχου, εφόσον αντιληφθούν κάποιο κενό ασφάλειας ή περιστατικό ασφάλειας, ενημερώνουν άμεσα τον Υπεύθυνο Ασφάλειας Δικτύων και Υπηρεσιών ή άλλο, ρητά εξουσιοδοτημένο για τον σκοπό αυτό, πρόσωπο.

[heading=article]
=== Ασφάλεια Εγκαταστάσεων και Συστημάτων

[heading=subarticle]
==== Φυσική Πρόσβαση και Περιβαλλοντική Ασφάλεια

[heading=custom]
===== Φυσική Πρόσβαση

[heading=paragraph]
====== {empty}

Ο πάροχος καθορίζει τα απαιτούμενα μέτρα

. για την αποτροπή της μη εξουσιοδοτημένης φυσικής πρόσβασης στις εγκαταστάσεις του στις οποίες είναι εγκατεστημένα ΠΕΣ, εξαιρουμένων εκείνων που χρησιμοποιούνται αποκλειστικά για την εξυπηρέτηση του κοινού,
. για τον έλεγχο της πρόσβασης στις εγκαταστάσεις του και
. για την προστασία των ΠΕΣ.

[heading=paragraph]
====== {empty}

Ο πάροχος διαθέτει και εφαρμόζει διαδικασία φυσικής πρόσβασης, στην οποία περιγράφονται αναλυτικά όλες οι ενέργειες που απαιτούνται για την πρόσβαση των εργαζομένων, συνεργατών και επισκεπτών του σε εγκαταστάσεις και σε χώρους εντός των εγκαταστάσεών του, όπου είναι εγκατεστημένα ΠΕΣ.

[heading=paragraph]
====== {empty}

Για την παροχή εξουσιοδότησης φυσικής πρόσβασης στους εργαζόμενους ή τους συνεργάτες του παρόχου σε εγκαταστάσεις και σε χώρους εντός των εγκαταστάσεών του όπου είναι εγκατεστημένα ΠΕΣ, προβλέπεται υποχρεωτικά προηγούμενη έγκριση από την αρμόδια διοικητική οντότητα ή το αρμόδιο φυσικό πρόσωπο.
Ο πάροχος διατηρεί αρχείο με το ιστορικό όλων των φυσικών προσβάσεων που έχουν εγκριθεί, στο οποίο καταγράφονται όλα τα στοιχεία που αφορούν εκάστη έγκριση (ενδεικτικά, χρονικό διάστημα, εγκατάσταση ή χώρο, είδος δικαιώματος πρόσβασης).

[heading=paragraph]
====== {empty}

Η φυσική πρόσβαση των εξουσιοδοτημένων προσώπων στις εγκαταστάσεις του παρόχου καταγράφεται (ονοματεπώνυμο, ιδιότητα, ώρα εισόδου και εξόδου) σε σχετικό αρχείο.
Σε περίπτωση πρόσβασης συνεργάτη του παρόχου ή άλλου επισκέπτη, στο αρχείο της παρούσας παραγράφου καταγράφεται επιπλέον ο λόγος της πρόσβασης, καθώς και τα στοιχεία (ονοματεπώνυμο και ιδιότητα) του εργαζομένου που πρόκειται να συναντήσει.

[heading=paragraph]
====== {empty}

Ο πάροχος ορίζει ασφαλείς χώρους εντός των εγκαταστάσεών του, στους οποίους εγκαθίστανται τα ΠΕΣ.
Οι χώροι αυτοί προστατεύονται με ισχυρούς μηχανισμούς ασφάλειας (ενδεικτικά, συστήματα άμεσης ανίχνευσης μη εξουσιοδοτημένης πρόσβασης και ειδοποίησης, συστήματα βιντεοεπιτήρησης) και ελέγχου πρόσβασης (ενδεικτικά, κάρτες ελεγχόμενης εισόδου) τηρουμένης της κείμενης νομοθεσίας περί προστασίας δεδομένων προσωπικού χαρακτήρα.
Η φυσική πρόσβαση στους χώρους της παρούσας παραγράφου καταγράφεται σύμφωνα με τις απαιτήσεις της παρ. 5.1.4 του παρόντος άρθρου.
Οι χώροι της παρούσας παραγράφου, καθώς και οι μηχανισμοί ασφάλειας και ελέγχου πρόσβασης, καταγράφονται σε αρχείο.

[heading=paragraph]
====== {empty}

Ο πάροχος λαμβάνει όλα τα αναγκαία και αναλογικά μέτρα φυσικής προστασίας και ελέγχου πρόσβασης για την προστασία των ΠΕΣ, τα οποία τοποθετούνται εκτός των εγκαταστάσεών του.
Στα ΠΕΣ αυτής της κατηγορίας περιλαμβάνεται ο εξοπλισμός που είναι εγκατεστημένος σε υπαίθριες κατασκευές (ενδεικτικά καμπίνες), σε εγκαταστάσεις άλλης εταιρείας και σε άλλους ιδιωτικούς ή δημόσιους χώρους, εντός ή εκτός της Ελληνικής επικράτειας.
Οι μηχανισμοί ασφάλειας για τις περιπτώσεις αυτές περιγράφονται σε αρχείο.

[heading=custom]
===== Περιβαλλοντική Ασφάλεια

[heading=paragraph]
====== {empty}

Ο πάροχος καθορίζει τα απαιτούμενα μέτρα για την προστασία από φυσικές καταστροφές που προκαλούνται από φαινόμενα όπως σεισμός, υγρασία, πλημμύρες, υπερθέρμανση, φωτιά, κεραυνός.

[heading=paragraph]
====== {empty}

Ο πάροχος λαμβάνει υπόψη του, κατά την επιλογή ή κατασκευή των εγκαταστάσεων στους οποίους εγκαθιστά ΠΕΣ, καθώς και κατά την τοποθέτηση εξοπλισμού και την υλοποίηση μέτρων φυσικής προστασίας, τις ιδιαίτερες φυσικές και άλλες συνθήκες οι οποίες επικρατούν στην περιοχή.
Ενδεικτικά αναφέρονται τα ακόλουθα μέτρα: ανιχνευτής φωτιάς, θερμοκρασίας και υγρασίας.

[heading=paragraph]
====== {empty}

Ο πάροχος επιλέγει, όπου είναι τεχνικά εφικτό, την υπόγεια εγκατάσταση καλωδίων σε σχέση με την εναέρια εγκατάσταση.

[heading=paragraph]
====== {empty}

Ο πάροχος μεριμνά για την τακτική συντήρηση των εγκαταστάσεων στις οποίες είναι εγκατεστημένα ΠΕΣ.

[heading=subarticle]
==== Ασφάλεια Λογικής Πρόσβασης

[heading=custom]
===== Λογική Πρόσβαση στα ΠΕΣ

[heading=paragraph]
====== {empty}

Ο πάροχος καθορίζει τη διαβάθμιση των επιπέδων πρόσβασης και θέτει τις απαιτήσεις για τον έλεγχο πρόσβασης στα ΠΕΣ.

[heading=paragraph]
====== {empty}

Οι απαιτήσεις της λογικής πρόσβασης ισχύουν για τους εργαζόμενους και συνεργάτες του παρόχου, οι οποίοι στο πλαίσιο της εργασίας τους αποκτούν πρόσβαση στα ΠΕΣ και στα σχετικά δεδομένα και τις πληροφορίες.
Η λογική πρόσβαση των εργαζομένων και συνεργατών περιορίζεται στις περιπτώσεις που αυτό είναι απαραίτητο για τις επιχειρησιακές ανάγκες του παρόχου.

[heading=paragraph]
====== {empty}

Για την απόκτηση πρόσβασης στα ΠΕΣ χρησιμοποιούνται κατάλληλοι μηχανισμοί ελέγχου πρόσβασης και αυθεντικοποίησης.
Ο έλεγχος της πρόσβασης και της αυθεντικοποίησης επιτυγχάνεται κατ’ ελάχιστον με τη χρήση ενός λογαριασμού πρόσβασης που αποτελείται από ένα ζεύγος ονόματος χρήστη και κωδικού πρόσβασης, ή άλλου μηχανισμού που εξασφαλίζει αντίστοιχο επίπεδο ασφάλειας.
Επιπλέον, για τα κρίσιμα ΠΕΣ, όπως αυτά έχουν αποτυπωθεί στην Αποτίμηση Κινδύνου στην οποία έχει προβεί ο πάροχος, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού, ο πάροχος υλοποιεί λύσεις ελέγχου πρόσβασης και αυθεντικοποίησης δύο παραγόντων (two-factor authentication).
Ως καλή πρακτική, η αυθεντικοποίηση δύο παραγόντων θα πρέπει να επιδιώκεται και για τους χρήστες με αυξημένα δικαιώματα διαχείρισης (διαχειριστές) των λοιπών ΠΕΣ.
Ο πάροχος διατηρεί αρχείο που αναφέρει αναλυτικά τους μηχανισμούς ελέγχου πρόσβασης και αυθεντικοποίησης για κάθε ΠΕΣ.

[heading=paragraph]
====== {empty}

Σε κάθε εργαζόμενο και συνεργάτη του παρόχου εκχωρείται προσωπικός λογαριασμός πρόσβασης ανά ΠΕΣ, ώστε να είναι δυνατή η αντιστοίχιση συγκεκριμένου προσώπου με τις ενέργειες που τελούνται σε κάθε ΠΕΣ.
Ο πάροχος διατηρεί αρχείο με την αντιστοίχιση των λογαριασμών πρόσβασης των εργαζόμενων και συνεργατών στους οποίους αυτοί έχουν αποδοθεί, ώστε να είναι δυνατό να διαπιστώνεται με βεβαιότητα ποιος είναι ο κάτοχος κάθε λογαριασμού πρόσβασης και για ποιο χρονικό διάστημα.

[heading=paragraph]
====== {empty}

Αναφορικά με τους λογαριασμούς πρόσβασης ισχύουν τα εξής:

. Αποφεύγεται η δημιουργία κοινών λογαριασμών πρόσβασης.
Σε περίπτωση που η δημιουργία τέτοιων λογαριασμών κρίνεται απαραίτητη, δικαιολογείται και τεκμηριώνεται η σχετική ανάγκη.
. Οι προκαθορισμένοι ή/και συστημικοί λογαριασμοί (system accounts) περιορίζονται στον ελάχιστο δυνατό αριθμό και η ανάγκη διατήρησής τους τεκμηριώνεται επαρκώς.
Αποφεύγεται η χρήση των εν λόγω λογαριασμών από φυσικά πρόσωπα.
. Σε περίπτωση χρήσης κοινών ή προκαθορισμένων-συστημικών λογαριασμών από φυσικά πρόσωπα, εξασφαλίζεται η αντιστοίχιση του συγκεκριμένου φυσικού προσώπου που αποκτά πρόσβαση σε ΠΕΣ με τις ενέργειες που τελούνται σε αυτό με κατάλληλο μηχανισμό, ο οποίος τεκμηριώνεται επαρκώς.
. Το υπόχρεο πρόσωπο διατηρεί αρχείο με την τεκμηρίωση αυτής της παραγράφου.

[heading=paragraph]
====== {empty}

Για τους λογαριασμούς πρόσβασης των παρ. 5.2.4 και 5.2.5 του παρόντος άρθρου, ο πάροχος διατηρεί αρχείο στο οποίο καταγράφεται το ιστορικό όλων των λογαριασμών που έχουν εγκριθεί και ενεργοποιηθεί στα ΠΕΣ (ενδεικτικά ανά ΠΕΣ: λογαριασμός πρόσβασης, δικαιώματα/επίπεδο πρόσβασης αυτού, χρονικό διάστημα ισχύος).

[heading=paragraph]
====== {empty}

Ο πάροχος καταγράφει σε αρχείο τους τρόπους πρόσβασης των εργαζομένων και συνεργατών του σε δεδομένα επικοινωνίας των συνδρομητών ή χρηστών των παρεχόμενων δικτύων ή υπηρεσιών (ενδεικτικά αναφέρονται οι τρόποι πρόσβασης μέσω εξειδικευμένων εφαρμογών, βάσεων δεδομένων και του συστήματος αρχείων του λειτουργικού συστήματος).

[heading=paragraph]
====== {empty}

Ο πάροχος διατηρεί και εφαρμόζει τις παρακάτω διαδικασίες:

[heading=paragraph,level=7]
====== Διαδικασία Διαχείρισης Χρηστών ΠΕΣ

[heading=paragraph,level=8]
====== {empty}

Στη Διαδικασία Διαχείρισης Χρηστών ΠΕΣ περιγράφεται με σαφήνεια ο τρόπος προσθήκης νέων χρηστών ΠΕΣ, η διαγραφή χρηστών ΠΕΣ, καθώς και η εκχώρηση και μεταβολή των δικαιωμάτων ή των επιπέδων πρόσβασης.

[heading=paragraph,level=8]
====== {empty}

Για κάθε μία εκ των ενεργειών που αναφέρονται στην παρ. 5.2.8.1.1. του παρόντος άρθρου προβλέπεται υποχρεωτικά προηγούμενη έγκριση από αρμόδιο εργαζόμενο του παρόχου.

[heading=paragraph,level=8]
====== {empty}

Στη Διαδικασία Διαχείρισης Χρηστών ΠΕΣ προβλέπεται η υποχρέωση τήρησης αρχείου των αιτήσεων που αφορούν σε κάθε μεταβολή στην κατάσταση πρόσβασης των χρηστών ΠΕΣ.

[heading=paragraph,level=7]
====== Διαδικασία Ελέγχου Ορθής Εφαρμογής των απαιτήσεων της Λογικής Πρόσβασης

[heading=paragraph,level=8]
====== {empty}

Στη Διαδικασία Ελέγχου Ορθής Εφαρμογής των απαιτήσεων της Λογικής Πρόσβασης περιγράφονται με σαφήνεια οι περιοδικοί έλεγχοι που πραγματοποιούνται, σε συμφωνία με τις αρχές του Ελέγχου Εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών της ενότητας 8.4 του άρθρου 8 του παρόντος Κανονισμού, αναφορικά με:

. Τον έλεγχο των δικαιωμάτων πρόσβασης των χρηστών ΠΕΣ, ήτοι, εάν το δικαίωμα πρόσβασης εκάστου χρήστη είναι πράγματι αυτό που του απεδόθη.
. Τον έλεγχο των λογαριασμών πρόσβασης, ήτοι, την αντιπαραβολή του αρχείου στο οποίο καταγράφεται το ιστορικό όλων των λογαριασμών (παρ. 5.2.6 του παρόντος άρθρου) με τους λογαριασμούς που προκύπτουν από έκαστο ΠΕΣ.
. Τον δειγματοληπτικό έλεγχο των αρχείων καταγραφής πρόσβασης (access logs) της παρ. 8.3.1.α του άρθρου 8 του παρόντος Κανονισμού για την ανακάλυψη ενδεχόμενων μη αιτιολογημένων προσβάσεων.

[heading=paragraph,level=8]
====== {empty}

Οι εν λόγω περιοδικοί έλεγχοι πραγματοποιούνται κατ’ ελάχιστον κάθε έξι (6) μήνες για τα κρίσιμα ΠΕΣ, όπως αυτά έχουν αποτυπωθεί στην Αποτίμηση Κινδύνου στην οποία έχει προβεί ο πάροχος, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού, και κατ’ ελάχιστον κάθε δώδεκα (12) μήνες για τα λοιπά ΠΕΣ.

[heading=paragraph]
====== {empty}

Σχετικά με τη δημιουργία και διαχείριση των λογαριασμών πρόσβασης, ο πάροχος διατηρεί (ανά ΠΕΣ ή συγκεντρωτικά) αρχείο, το οποίο περιλαμβάνει τα ακόλουθα:

. Περιγραφή των κανόνων σύμφωνα με τους οποίους γίνεται η δημιουργία ενός ονόματος χρήστη,
. περιγραφή των κανόνων σύμφωνα με τους οποίους γίνεται η δημιουργία ενός κωδικού πρόσβασης,
. τον τρόπο σύμφωνα με τον οποίο αποδίδεται με ασφάλεια σε κάθε εργαζόμενο και συνεργάτη του παρόχου το όνομα χρήστη και ο κωδικός πρόσβασης,
. τον τρόπο σύμφωνα με τον οποίο επιτυγχάνεται η τακτική αλλαγή των κωδικών πρόσβασης και εν γένει η διαχείρισή τους,
. περιγραφή των όρων χρήσης των κωδικών πρόσβασης από τους εργαζόμενους και συνεργάτες του παρόχου,
. τη διαδικασία, σύμφωνα με την οποία διενεργείται έλεγχος για την ορθή εφαρμογή των παραπάνω κανόνων και διαδικασιών, σε συμφωνία με τις αρχές του Ελέγχου Εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών της ενότητας 8.4 του άρθρου 8 του παρόντος Κανονισμού.

[heading=paragraph]
====== {empty}

Για την υλοποίηση των υποχρεώσεων της παρ. 5.2.9 του παρόντος άρθρου, ο πάροχος λαμβάνει υπόψη τις συνήθεις καλές πρακτικές από την επιστήμη και την τεχνολογία και ιδιαίτερα τις παρακάτω απαιτήσεις:

[heading=paragraph,level=7]
====== {empty}

Τα ονόματα χρήστη δεν υποδηλώνουν τον ρόλο των εργαζομένων και συνεργατών του παρόχου στο αντίστοιχο ΠΕΣ (ενδεικτικά, δεν είναι παράγωγα της λέξης admin).

[heading=paragraph,level=7]
====== {empty}

Οι χρησιμοποιούμενοι κωδικοί πρόσβασης είναι ισχυροί και έχουν δημιουργηθεί με τρόπο που αποτρέπει τον προσδιορισμό τους με εύκολο τρόπο.
Ειδικότερα, οι κωδικοί πρόσβασης δημιουργούνται με συνδυασμό δύο (2) τουλάχιστον διαφορετικών ειδών χαρακτήρων (αριθμοί, γράμματα, ειδικοί χαρακτήρες).
Οι κωδικοί πρόσβασης έχουν υποχρεωτικά ένα επαρκές, με βάση τις συνήθεις καλές πρακτικές, ελάχιστο μήκος, απαγορεύεται η χρήση πρόσφατων κωδικών στη διαδικασία αλλαγής τους και δεν ακολουθούνται συγκεκριμένα υποδείγματα κατά τη δημιουργία τους.

[heading=paragraph,level=7]
====== {empty}

Οι κωδικοί πρόσβασης αλλάζουν περιοδικά, σε συχνότητα που καθορίζεται ρητά ανά ΠΕΣ και αναφέρεται σε αρχείο που διατηρεί ο πάροχος.
Ο πάροχος χρησιμοποιεί και καταγράφει στο εν λόγω αρχείο τους τρόπους με τους οποίους επιβάλλει την περιοδική αλλαγή των κωδικών πρόσβασης.
Σε χαρακτηριστικές περιπτώσεις όπως είναι, ενδεικτικά, η παραβίαση ενός λογαριασμού πρόσβασης, προβλέπεται η άμεση αλλαγή του αντίστοιχου κωδικού πρόσβασης.

[heading=paragraph,level=7]
====== {empty}

Σε περίπτωση επαναλαμβανόμενης εισαγωγής λανθασμένων κωδικών πρόσβασης (ενδεικτικά, μετά από τρεις συνεχόμενες αποτυχημένες απόπειρες εισαγωγής του) ο λογαριασμός πρόσβασης αδρανοποιείται ή μπορεί να χρησιμοποιηθεί μόνο μετά την πάροδο ενός προκαθορισμένου χρονικού διαστήματος.

[heading=paragraph,level=7]
====== {empty}

Οι κωδικοί πρόσβασης διατηρούνται κρυπτογραφημένοι στα ΠΕΣ.

[heading=custom]
===== Πρόσθετες Απαιτήσεις αναφορικά με την Απομακρυσμένη Λογική Πρόσβαση

[heading=paragraph]
====== {empty}

Ο πάροχος καθορίζει τη διαβάθμιση των επιπέδων πρόσβασης και θέτει τις απαιτήσεις για τον έλεγχο της απομακρυσμένης πρόσβασης στα ΠΕΣ.

[heading=paragraph]
====== {empty}

Οι απαιτήσεις για την Απομακρυσμένη Λογική Πρόσβαση ισχύουν για τους εργαζόμενους και συνεργάτες του παρόχου, οι οποίοι στο πλαίσιο της εργασίας τους αποκτούν απομακρυσμένη πρόσβαση στα ΠΕΣ και στα σχετικά δεδομένα και τις πληροφορίες.

[heading=paragraph]
====== {empty}

Η απομακρυσμένη πρόσβαση εργαζομένων και συνεργατών του παρόχου στα ΠΕΣ του περιορίζεται στις περιπτώσεις που αυτό είναι απαραίτητο για τις επιχειρησιακές του ανάγκες.

[heading=paragraph]
====== {empty}

Ο πάροχος διατηρεί αρχείο, στο οποίο καταγράφονται τα ΠΕΣ στα οποία επιτρέπεται η απομακρυσμένη πρόσβαση και οι τεχνικοί τρόποι απομακρυσμένης ασφαλούς πρόσβασης εργαζομένων και συνεργατών του, για κάθε ΠΕΣ στο οποίο έχει επιτραπεί η απομακρυσμένη πρόσβαση.

[heading=paragraph]
====== {empty}

Ο πάροχος τηρεί αρχείο με τους εργαζομένους και συνεργάτες του (ονοματεπώνυμο και ιδιότητα), οι οποίοι έχουν εξουσιοδοτηθεί για χρήση της απομακρυσμένης πρόσβασης.
Στο εν λόγω αρχείο καταγράφονται τα δικαιώματα πρόσβασης που τους αντιστοιχούν για κάθε ΠΕΣ.

[heading=paragraph]
====== {empty}

Η απομακρυσμένη πρόσβαση των εργαζομένων και συνεργατών του παρόχου πραγματοποιείται με χρήση μηχανισμών ασφαλούς αυθεντικοποίησης και κρυπτογράφησης (π.χ. μέσω Εικονικών Ιδιωτικών Δικτύων (Virtual Private Networks - VPN)).

[heading=paragraph]
====== {empty}

Ο πάροχος εξασφαλίζει ότι κάθε σύνδεση εργαζομένων και συνεργατών του στα ΠΕΣ αυτού επιτρέπεται μόνο εφόσον η σύνδεση αυτή δεν παραβιάζει κάποιον από τους κανόνες ασφάλειας του δικτύου του.

[heading=paragraph]
====== {empty}

Η απομακρυσμένη πρόσβαση των συνεργατών του παρόχου στα συστήματά του επιτρέπεται για την υλοποίηση συγκεκριμένης εργασίας, η οποία πραγματοποιείται εντός καθορισμένου χρονικού διαστήματος.
Ο πάροχος επιτρέπει την απομακρυσμένη πρόσβαση των συνεργατών του για τον σκοπό αυτό μόνο κατόπιν έγκρισης σχετικού αιτήματος, στο οποίο θα αναφέρεται η εργασία, τα ΠΕΣ στα οποία θα πραγματοποιηθεί η πρόσβαση, καθώς και το χρονικό διάστημα που απαιτείται.
Ο περιορισμός του χρονικού διαστήματος μπορεί να υλοποιείται με τη χρήση προσωρινών κωδικών, οι οποίοι θα μεταβάλλονται μετά το πέρας του προκαθορισμένου χρονικού διαστήματος, ή με την απενεργοποίηση των λογαριασμών μετά το πέρας του διαστήματος αυτού ή με άλλον αντίστοιχο μηχανισμό.
Ο πάροχος τηρεί αρχείο με όλες τις πληροφορίες της παρούσας παραγράφου.

[heading=paragraph]
====== {empty}

Ο πάροχος διατηρεί και εφαρμόζει συγκεκριμένη διαδικασία διαχείρισης των λογαριασμών απομακρυσμένης πρόσβασης των εργαζομένων και συνεργατών του, η οποία είναι σύμφωνη με τις απαιτήσεις που αναφέρονται στην ενότητα 5.2.Β του παρόντος άρθρου.

[heading=paragraph]
====== {empty}

Ο πάροχος ελέγχει, κατ’ ελάχιστον, κάθε τρεις (3) μήνες α) την αντιστοίχιση των λογαριασμών απομακρυσμένης πρόσβασης και του αρχείου της παρ. 5.2.15 του παρόντος άρθρου, και β) την υλοποίηση των απαιτούμενων μεταβολών των κωδικών και απενεργοποιήσεων των λογαριασμών της παρ. 5.2.18 του παρόντος άρθρου, σε συμφωνία με τις αρχές του Ελέγχου Εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών της ενότητας 8.4 του άρθρου 8 του παρόντος Κανονισμού.

[heading=custom]
===== Ειδικές Απαιτήσεις σχετικά με τους Συνδρομητές ή Χρήστες των Παρεχόμενων Δικτύων ή Υπηρεσιών

[heading=paragraph]
====== {empty}

Ο πάροχος διατηρεί αρχείο που αναφέρει αναλυτικά τους μηχανισμούς ελέγχου πρόσβασης και αυθεντικοποίησης που χρησιμοποιούνται για την πρόσβαση των συνδρομητών ή χρηστών του στις υπηρεσίες ή/και τα δίκτυα που παρέχει.

[heading=paragraph]
====== {empty}

Ο πάροχος διατηρεί και εφαρμόζει συγκεκριμένη διαδικασία διαχείρισης των λογαριασμών πρόσβασης των συνδρομητών ή χρηστών στις υπηρεσίες ή/και τα δίκτυα που παρέχει, στην οποία περιγράφεται με σαφήνεια κατ’ ελάχιστον ο τρόπος προσθήκης και κατάργησης λογαριασμών πρόσβασης, καθώς και η απόδοση του ονόματος χρήστη και του κωδικού πρόσβασης στους συνδρομητές ή χρήστες των παρεχόμενων δικτύων ή υπηρεσιών.
Κατά τη δημιουργία ή επανέκδοση του κωδικού πρόσβασης, ο πάροχος τον δημιουργεί με τρόπο που αποτρέπει τον εύκολο προσδιορισμό του.
Ο πάροχος ενημερώνει με κάθε πρόσφορο μέσο τους συνδρομητές ή χρήστες των παρεχόμενων δικτύων ή υπηρεσιών σχετικά με την αναγκαιότητα αλλαγής του κωδικού πρόσβασης, καθώς και σχετικά με ενδεδειγμένους κανόνες δημιουργίας ισχυρών κωδικών πρόσβασης.

[heading=paragraph]
====== {empty}

Ο πάροχος πραγματοποιεί ελέγχους, κατ’ ελάχιστον κάθε δώδεκα (12) μήνες, σχετικά με την αλλαγή του κωδικού πρόσβασης που αποδίδει στους συνδρομητές ή χρήστες των παρεχόμενων δικτύων ή υπηρεσιών και τους ενημερώνει εκ νέου για την αναγκαιότητα αλλαγής των κωδικών πρόσβασης σε περίπτωση που δεν έχουν προβεί στη σχετική αλλαγή, σε συμφωνία με τις αρχές του Ελέγχου Εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών της ενότητας 8.4 του άρθρου 8 του παρόντος Κανονισμού.

[heading=paragraph]
====== {empty}

Σε περίπτωση που προσφέρεται στους συνδρομητές ή χρήστες των παρεχόμενων δικτύων ή υπηρεσιών του παρόχου η δυνατότητα να αποκτήσουν πρόσβαση σε δεδομένα επικοινωνίας τους (ενδεικτικά, εξερχόμενες κλήσεις, ηλεκτρονικό ταχυδρομείο) μέσω συγκεκριμένου ιστoτόπου, ο πάροχος χρησιμοποιεί τους ευρέως αποδεκτούς μηχανισμούς ασφαλούς αυθεντικοποίησης και κρυπτογράφησης, του οποίους και περιγράφει σε σχετικό αρχείο που διατηρεί.
Ο πάροχος καταγράφει τις σχετικές προσβάσεις και ενέργειες των συνδρομητών ή χρηστών των παρεχόμενων δικτύων ή υπηρεσιών, σύμφωνα με τις απαιτήσεις της παρ. 8.3.1 του άρθρου 8 του παρόντος Κανονισμού.

[heading=paragraph]
====== {empty}

Οι κωδικοί πρόσβασης των συνδρομητών ή χρηστών των παρεχόμενων δικτύων ή υπηρεσιών διατηρούνται κρυπτογραφημένοι στα ΠΕΣ.

[heading=subarticle]
==== Ασφάλεια Δικτύου

[heading=custom]
===== Γενικές Αρχές Μηχανισμών και Συστημάτων Ασφάλειας Δικτύου

[heading=paragraph]
====== {empty}

Ο πάροχος καταρτίζει και διατηρεί διαρκώς ενημερωμένο αρχείο στο οποίο ορίζονται οι μηχανισμοί και τα συστήματα που χρησιμοποιούνται σε υλικό και λογισμικό για τους σκοπούς της Ασφάλειας Δικτύου.
Οι τρόποι λειτουργίας και τεχνικής διαμόρφωσής τους λαμβάνουν υπόψη τις διεθνείς, ευρέως αποδεκτές πρακτικές και πρότυπα, καθώς και την Αποτίμηση Κινδύνου στην οποία έχει προβεί ο πάροχος, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού.
Οι μηχανισμοί και τα συστήματα της Ασφάλειας Δικτύου περιλαμβάνουν, ενδεικτικά και όχι περιοριστικά: τείχη προστασίας, συστήματα ανίχνευσης και αποτροπής εισβολών (intrusion detection and prevention systems), λίστες ελέγχου πρόσβασης (access control lists), εικονικά ιδιωτικά δίκτυα, εικονικά τοπικά δίκτυα.

[heading=paragraph]
====== {empty}

Η εγκατάσταση, η επικαιροποίηση και η διαχείριση των αναφερόμενων στην παράγραφο 5.3.1 του παρόντος άρθρου μηχανισμών και συστημάτων είναι σύμφωνη με τις αρχές της Διαχείρισης ΠΕΣ της ενότητας 6.2 του άρθρου 6 του παρόντος Κανονισμού και συμπεριλαμβάνει τους κανόνες πρόσβασης ή ελέγχου που έχουν τεθεί στους εν λόγω μηχανισμούς και συστήματα (ενδεικτικά αναφέρεται η επικαιροποίηση του συστήματος ανίχνευσης και αποτροπής εισβολών με υπογραφές νέων εισβολών ή επιθέσεων).

[heading=paragraph]
====== {empty}

Η λειτουργία των αναφερομένων στην παρ. 5.3.1 του παρόντος άρθρου μηχανισμών και συστημάτων είναι συνεχής, εξαιρουμένων των περιπτώσεων προγραμματισμένης συντήρησης ή αναβάθμισης, σύμφωνα με τις αρχές της Διαχείρισης ΠΕΣ της ενότητας 6.2 του άρθρου 6 του παρόντος Κανονισμού.

[heading=custom]
===== Λογικός Διαχωρισμός και Κατάτμηση Δικτύων του Παρόχου

[heading=paragraph]
====== {empty}

Ο πάροχος καταρτίζει και διατηρεί διαρκώς ενημερωμένο αρχείο, στο οποίο, με βάση τους αναφερόμενους στην παρ. 5.3.1 του παρόντος άρθρου μηχανισμούς και συστήματα

. περιγράφεται ο λογικός διαχωρισμός και η κατάτμηση των δικτύων του με αντίστοιχη σχηματική απεικόνιση,
. περιγράφεται η αρχιτεκτονική που έχει υλοποιηθεί και
. καταγράφονται όλα τα ΠΕΣ και η ζώνη ασφάλειας στην οποία έχουν τοποθετηθεί.

Ο πάροχος διατηρεί τις προηγούμενες εκδόσεις του εν λόγω αρχείου και το χρονικό διάστημα ισχύος εκάστης.

[heading=paragraph]
====== {empty}

Σε περίπτωση που ο πάροχος διαθέτει στο κοινό υπηρεσίες ηλεκτρονικών επικοινωνιών που απαιτούν πρόσβαση σε εξυπηρετητές από εξωτερικά δίκτυα (αναφέρονται ενδεικτικά οι υπηρεσίες ηλεκτρονικού ταχυδρομείου), τα ΠΕΣ που προσφέρουν τις εν λόγω υπηρεσίες τοποθετούνται σε μία ή περισσότερες αποστρατικοποιημένες ζώνες (DeMilitarized Zone, DMZ).

[heading=paragraph]
====== {empty}

Τα ΠΕΣ του παρόχου που χρησιμοποιούνται από τους εργαζόμενους και συνεργάτες του για την εκτέλεση των επιχειρησιακών διαδικασιών και λειτουργιών (ενδεικτικά, τα συστήματα διαχείρισης και εποπτείας, τα συστήματα καταγραφής, τα συστήματα χρέωσης συνδρομητών, οι βάσεις δεδομένων που περιέχουν δεδομένα επικοινωνίας και οι εφαρμογές πρόσβασης σε δεδομένα επικοινωνίας) εντάσσονται σε μία ή περισσότερες εσωτερικές έμπιστες ζώνες, ανάλογα με τις απαιτήσεις ασφάλειας και την κρισιμότητά τους.

[heading=paragraph]
====== {empty}

Τα ΠΕΣ του παρόχου, ιδίως αυτά που δεν τοποθετούνται σε αποστρατικοποιημένες ή έμπιστες ζώνες (ενδεικτικά, τα δίκτυα πρόσβασης/μετάδοσης, οι συσκευές και κόμβοι διασύνδεσης με τρίτα/εξωτερικά δίκτυα), είναι δυνατό, ανάλογα με την τεχνολογία τους, να υποστηρίζουν την προαιρετική χρήση συγκεκριμένων μηχανισμών ασφάλειας.
Στην περίπτωση αυτή, ο πάροχος επιλέγει, ενεργοποιεί και παραμετροποιεί όλους τους κατάλληλους μηχανισμούς ασφάλειας, εκμεταλλευόμενος τις δυνατότητες και μεθόδους ασφάλειας που διαθέτει (ενδεικτικά αναφέρεται η κρυπτογράφηση), τις διεθνείς, ευρέως αποδεκτές πρακτικές και πρότυπα, και τα αποτελέσματα που προκύπτουν από την Αποτίμηση Κινδύνου, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού.
Για τα ΠΕΣ της παρούσας παραγράφου, ο πάροχος διατηρεί αρχείο με πλήρη ανάλυση των μέτρων προστασίας και ασφάλειας που έχουν υλοποιηθεί σε αυτά, με σκοπό την ασφάλεια δικτύων και υπηρεσιών του.

[heading=subarticle]
==== Προστασία από Κακόβουλο Λογισμικό και Ακεραιότητα των ΠΕΣ

[heading=paragraph]
===== {empty}

Ο πάροχος λαμβάνει όλα τα απαραίτητα οργανωτικά, τεχνικά και άλλα μέτρα ασφάλειας, τα οποία αποσκοπούν στην αποτροπή, ανίχνευση και αντιμετώπιση κακόβουλου λογισμικού.
Σε περίπτωση ανίχνευσης κακόβουλου λογισμικού, ο πάροχος ενεργοποιεί τους κατάλληλους μηχανισμούς που διαθέτει για τον περιορισμό της εξάπλωσής του και επιπλέον πραγματοποιεί άμεση αξιολόγηση του περιστατικού και, αναλόγως της κρισιμότητάς του, ενεργοποιεί τη Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας, σύμφωνα με την ενότητα 7.1 του άρθρου 7 του παρόντος Κανονισμού.

[heading=paragraph]
===== {empty}

Ο πάροχος ενημερώνει τους εργαζόμενους και συνεργάτες του αναφορικά με τους κινδύνους από κακόβουλο λογισμικό, καθώς και σχετικά με τις υποχρεώσεις τους σε σχέση με τα μέτρα προστασίας έναντι του κακόβουλου λογισμικού.

[heading=paragraph]
===== {empty}

Ο πάροχος λαμβάνει τα απαραίτητα οργανωτικά και τεχνικά μέτρα, τα οποία αποσκοπούν στην αποτροπή της παραποίησης του λογισμικού των ΠΕΣ, κατά την προμήθεια, εγκατάσταση και λειτουργία τους και ιδιαίτερα στην περίπτωση κατά την οποία πραγματοποιούνται οι αναγκαίες αναβαθμίσεις, ενημερώσεις και διορθώσεις (updates, patches).
Ο πάροχος, σε συμφωνία με τις αρχές του Ελέγχου Εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών της ενότητας 8.4 του άρθρου 8 του παρόντος Κανονισμού, πραγματοποιεί έλεγχο της ακεραιότητας του λογισμικού των ΠΕΣ.
Ο έλεγχος αυτός έχει ως σκοπό τη διαπίστωση της μη ύπαρξης στα ΠΕΣ λογισμικού πέραν αυτού που έχει επισήμως προμηθευτεί ο πάροχος.

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί αρχείο στο οποίο καταγράφονται οι λεπτομέρειες εφαρμογής των απαιτήσεων που ορίζονται στην παρούσα ενότητα.

[heading=subarticle]
==== Χρήση Κρυπτογραφίας

[heading=paragraph]
===== {empty}

Ο πάροχος χρησιμοποιεί τους κατάλληλους αλγόριθμους και συστήματα κρυπτογράφησης για την επαρκή προστασία των δεδομένων επικοινωνίας ή άλλων πληροφοριών που μπορεί να οδηγήσουν σε αποκάλυψη δεδομένων επικοινωνίας των συνδρομητών ή χρηστών των παρεχόμενων δικτύων ή υπηρεσιών (ενδεικτικά αναφέρονται κωδικοί πρόσβασης και δεδομένα διάρθρωσης των ΠΕΣ) κατά την αποθήκευση και μεταφορά τους σε ΠΕΣ, καθώς και τα ελάχιστα χαρακτηριστικά ασφάλειας των συστημάτων κρυπτογράφησης.

[heading=paragraph]
===== {empty}

Ο πάροχος εφαρμόζει συστήματα κρυπτογράφησης για την επαρκή προστασία των δεδομένων επικοινωνίας κατά την αποθήκευση και μεταφορά τους μέσω δικτύων.

[heading=paragraph]
===== {empty}

Η κρυπτογράφηση εφαρμόζεται στα ΠΕΣ με βάση τα αποτελέσματα που προκύπτουν από την Αποτίμηση Κινδύνου, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού.

[heading=paragraph]
===== {empty}

Σε περίπτωση που χρησιμοποιούνται αλγόριθμοι και συστήματα κρυπτογράφησης, συμπεριλαμβανομένων και των αλγορίθμων ψηφιακής υπογραφής, λαμβάνονται υπόψη τα διεθνώς ευρέως αποδεκτά πρότυπα.

[heading=paragraph]
===== {empty}

Το μήκος κλειδιού που χρησιμοποιείται λαμβάνει υπόψη τα διεθνώς και ευρέως αποδεκτά πρότυπα, ανάλογα με τον χρησιμοποιούμενο αλγόριθμο κρυπτογράφησης και με τα αποτελέσματα που προκύπτουν από την Αποτίμηση Κινδύνου, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού.

[heading=paragraph]
===== {empty}

Ο πάροχος αποτρέπει τη μη εξουσιοδοτημένη πρόσβαση στα κλειδιά τα οποία χρησιμοποιούνται για κρυπτογράφηση, αυθεντικοποίηση ή ψηφιακή υπογραφή.

[heading=paragraph]
===== {empty}

[.ed]
--
Σε περίπτωση που χρησιμοποιούνται ασύμμετροι κρυπτογραφικοί αλγόριθμοι

. για λογική πρόσβαση σε ΠΕΣ,
. για κρυπτογράφηση ή
. για ψηφιακή υπογραφή,

κάθε ζεύγος ιδιωτικού/δημόσιου κλειδιού αντιστοιχεί σε έναν μοναδικό χρήστη και το αντίστοιχο ιδιωτικό κλειδί είναι γνωστό μόνο στον συγκεκριμένο χρήστη, στον οποίο αντιστοιχεί.
--

[heading=paragraph]
===== {empty}

Σε περίπτωση που ο πάροχος χρησιμοποιεί ψηφιακά πιστοποιητικά δημόσιων κλειδιών (digital certificates), τα οποία παράγονται από παρόχους υπηρεσιών πιστοποίησης (certification service providers), εξασφαλίζει ότι ο πάροχος υπηρεσιών πιστοποίησης συμμορφώνεται με την κείμενη νομοθεσία.

[heading=paragraph]
===== {empty}

Σε περίπτωση που ο πάροχος παράγει και διαχειρίζεται κλειδιά κρυπτογράφησης, τα οποία χρησιμοποιούνται σε ΠΕΣ, διατηρεί και εφαρμόζει κατάλληλες διαδικασίες για τη δημιουργία, πιστοποίηση, διανομή και ανάκληση των κρυπτογραφικών κλειδιών.

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί αρχείο, στο οποίο καταγράφονται οι λεπτομέρειες εφαρμογής των απαιτήσεων που ορίζονται στην παρούσα ενότητα.

[heading=article]
=== Διαχείριση Λειτουργίας

[heading=subarticle]
==== Παρακολούθηση Δικτύου

[heading=paragraph]
===== {empty}

Ο πάροχος παρακολουθεί συνεχώς την υφιστάμενη λειτουργία του δικτύου και των υπηρεσιών, καταγράφει και αναλύει τα προβλήματα και προβλέπει τις μελλοντικές ανάγκες, ώστε να προβαίνει έγκαιρα στις απαραίτητες ενέργειες για την ασφάλεια του δικτύου και των υπηρεσιών του με σκοπό τη διασφάλιση του απορρήτου των επικοινωνιών.

[heading=paragraph]
===== {empty}

Ο πάροχος εξετάζει, αξιολογεί και αξιοποιεί πιθανές αναφορές παραπόνων που υποβάλλονται από χρήστες του δικτύου και των υπηρεσιών του σχετικά με προβλήματα που παρουσιάζονται κατά την παροχή της υπηρεσίας.

[heading=subarticle]
==== Διαχείριση ΠΕΣ

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί και εφαρμόζει διαδικασία διαχείρισης ΠΕΣ, η οποία προσδιορίζει τις απαιτήσεις που πρέπει να ικανοποιούνται καθ’ όλη τη διάρκεια του κύκλου ζωής των ΠΕΣ.
Κατ’ ελάχιστον η διαδικασία περιγράφει τα ακόλουθα στάδια:

. Προμήθειας/Ανάπτυξης Υλικού και Λογισμικού,
. Εγκατάστασης/Αρχικής Λειτουργίας Υλικού και Λογισμικού,
. Λειτουργίας Υλικού και Λογισμικού και
. Διαγραφής/Απόσυρσης Υλικού και Λογισμικού

[heading=paragraph]
===== {empty}

[.ed]
--
Κατά το στάδιο της Προμήθειας/Ανάπτυξης Υλικού και Λογισμικού των ΠΕΣ, ο πάροχος:

. Πραγματοποιεί αρχικά Αποτίμηση Κινδύνου για τον εντοπισμό των πιθανών απειλών, ευπαθειών και κινδύνων του υπό προμήθεια/ανάπτυξη ΠΕΣ, αναφορικά με την ασφάλεια δικτύων και υπηρεσιών, σε συμφωνία με τις αρχές της Διαχείρισης Κινδύνου της ενότητας 3.2 του άρθρου 3 του παρόντος Κανονισμού.

. συντάσσει κατάλογο
[lowerroman]
.. κανόνων ασφάλειας που αφορούν σε ρυθμίσεις ή χαρακτηριστικά του υπό προμήθεια/ανάπτυξη ΠΕΣ σχετικά με την ασφάλεια δικτύων και υπηρεσιών,
.. ελάχιστων κανόνων που αφορούν στα χαρακτηριστικά διαμόρφωσης και διαχείρισης του υπό προμήθεια/ανάπτυξη ΠΕΣ, καθώς και
.. παραμέτρων διαμόρφωσης της καταγραφής της πρόσβασης και των ενεργειών,

ώστε να επιτυγχάνεται η συμμόρφωση με τις προδιαγραφές ασφάλειας που καθορίζονται από τα αποτελέσματα της Αποτίμησης Κινδύνου και από τις βέλτιστες πρακτικές ασφάλειας.
--

Οι ως άνω κανόνες γίνονται αποδεκτοί από όλα τα εμπλεκόμενα μέρη (π.χ. συνεργαζόμενες εταιρείες, υπαλλήλους του υπόχρεου προσώπου που αναπτύσσουν εσωτερικά στην εταιρεία το λογισμικό) και τηρούνται σε αρχείο από το υπόχρεο πρόσωπο.

[heading=paragraph]
===== {empty}

Κατά το στάδιο της Εγκατάστασης/Αρχικής Λειτουργίας Υλικού και Λογισμικού των ΠΕΣ, ο πάροχος:

. πραγματοποιεί δοκιμές για τον έλεγχο της συμμόρφωσης με τους κανόνες ασφάλειας της προηγούμενης παραγράφου,
. καταγράφει και διατηρεί σε αρχείο τις δοκιμές και τα αποτελέσματα αυτών.
Το αρχείο αυτό επισυνάπτεται στη συνολική έκθεση αποδοχής του ΠΕΣ και τηρείται αδιάλειπτα.

[heading=paragraph]
===== {empty}

Κατά το στάδιο Λειτουργίας Υλικού και Λογισμικού των ΠΕΣ, ο πάροχος:

. εκτελεί προληπτική συντήρηση του ΠΕΣ, βάσει προδιαγεγραμμένου χρονοδιαγράμματος, προκειμένου να ελαχιστοποιηθεί η πιθανότητα δυσλειτουργίας του δικτύου και των παρεχόμενων υπηρεσιών.
Ειδικότερα, ο πάροχος διαθέτει κατάλληλους μηχανισμούς ώστε να προλαβαίνει τυχόν βλάβες ή να τις αποκαθιστά άμεσα σε περίπτωση εμφάνισής τους, όπως, ενδεικτικά, βλαβοληψία, διαχείριση ανταλλακτικών, διαδικασία εσωτερικής κλιμάκωσης αναφοράς προβλημάτων, δείκτες αποκατάστασης βλαβών με τους προμηθευτές,
. εξασφαλίζει ότι υπάρχουν, ανά πάσα στιγμή, διαθέσιμα αντίγραφα ασφαλείας της πλέον πρόσφατης διαμόρφωσης του ΠΕΣ, τα οποία είναι απαραίτητα για την αποκατάσταση του δικτύου του και των παρεχόμενων υπηρεσιών.
Τα αντίγραφα ασφαλείας φυλάσσονται σε προστατευμένο χώρο,
. πραγματοποιεί στο λογισμικό/υλικό του ΠΕΣ, αμελλητί, τις αλλαγές (εισαγωγή/μεταβολή/διαγραφή) που σχετίζονται με την ασφάλεια δικτύων και υπηρεσιών,
. διατηρεί αρχείο για οποιαδήποτε αλλαγή υλικού ή λογισμικού ΠΕΣ, στο οποίο καταγράφεται η ημερομηνία, ο τρόπος, η αιτιολόγηση και το προσωπικό που πραγματοποίησε τις αλλαγές.
Το αρχείο ενημερώνεται και διατηρείται από εξουσιοδοτημένη προς τούτο διοικητική οντότητα ή προσωπικό του παρόχου.

[heading=paragraph]
===== {empty}

Κατά το στάδιο της Διαγραφής/Απόσυρσης Υλικού και Λογισμικού των ΠΕΣ, ο πάροχος:

. ορίζει συγκεκριμένες ενέργειες προκειμένου να διασφαλίζεται ότι, με την επιφύλαξη τήρησης υποχρεώσεων που τυχόν απορρέουν από άλλες διατάξεις της κείμενης νομοθεσίας, όταν διαγράφεται και αποσύρεται υλικό ή λογισμικό των ΠΕΣ, η πληροφορία που έχει εγγραφεί στον εξοπλισμό των ΠΕΣ (π.χ. σε μνήμες ROM, σκληρούς δίσκους, μαγνητικές ταινίες κ.λπ.) διαγράφεται οριστικά και δεν μπορεί να χρησιμοποιηθεί από τρίτους.
. διατηρεί αρχείο στο οποίο καταγράφονται τα ΠΕΣ, τα οποία αποσύρονται.

[heading=article]
=== Διαχείριση Περιστατικών Ασφάλειας

[heading=subarticle]
==== Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί και εφαρμόζει Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας, η οποία ενεργοποιείται αμελλητί σε κάθε περίπτωση περιστατικού ασφάλειας, όπως ορίζεται στο άρθρο 2 του παρόντος Κανονισμού, με σκοπό τη διαχείριση των περιστατικών.

[heading=paragraph]
===== {empty}

Η Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας προβλέπει κατ’ ελάχιστον τις ακόλουθες ενέργειες:

. την οργάνωση του προσωπικού του παρόχου (ορισμοί ρόλων και αρμοδιοτήτων), με σκοπό την αποτελεσματική διαχείριση των περιστατικών ασφάλειας,
. τον εντοπισμό, την καταγραφή και αρχειοθέτηση των περιστατικών ασφάλειας,
. τη διερεύνηση των αιτιών και τον προσδιορισμό των τεχνικών ή/και οργανωτικών αδυναμιών στις οποίες ενδεχομένως οφείλεται το περιστατικό ασφάλειας και την καταγραφή τους,
. την καταγραφή και υλοποίηση των διορθωτικών μέτρων και ενεργειών με συγκεκριμένο χρονοδιάγραμμα και
. την ενημέρωση του Υπεύθυνου Ασφάλειας Δικτύων και Υπηρεσιών, των αρμοδίων στελεχών του παρόχου, των αρμοδίων Αρχών και των θιγόμενων συνδρομητών ή χρηστών των παρεχόμενων δικτύων και υπηρεσιών, σύμφωνα με την κείμενη νομοθεσία.

[heading=paragraph]
===== {empty}

Ο πάροχος ελέγχει σε τακτά χρονικά διαστήματα την ετοιμότητα ενεργοποίησης της Διαδικασίας Διαχείρισης Περιστατικών Ασφάλειας, και αξιολογεί και ανανεώνει την εν λόγω Διαδικασία, με βάση τα αποτελέσματα των ελέγχων και τα προηγούμενα περιστατικά.

[heading=paragraph]
===== {empty}

Ο πάροχος παρέχει στους συνδρομητές ή χρήστες των δικτύων ή υπηρεσιών του τη δυνατότητα να καταγγέλλουν με απλά μέσα (π.χ. μέσω του ιστοτόπου του) την ενδεχόμενη παραβίαση της ασφάλειας των παρεχόμενων δικτύων ή υπηρεσιών.

[heading=subarticle]
==== Αναφορά Περιστατικών Ασφάλειας

[heading=paragraph]
===== {empty}

Ο πάροχος κοινοποιεί το ως άνω περιστατικό ασφάλειας στην ΑΔΑΕ, ως ακολούθως:

[uppergreek]
. Ο πάροχος υποβάλλει αμελλητί στην ΑΔΑΕ την «Έκθεση Αρχικής Αναφοράς Περιστατικού Ασφάλειας», στην οποία καταγράφονται, κατ’ ελάχιστον, τα ακόλουθα:
[lowerroman]
.. Το είδος του περιστατικού ασφάλειας.
.. Περιεκτική περιγραφή του περιστατικού ασφάλειας.
.. Σύντομη αναφορά των αιτιών οι οποίες προκάλεσαν το περιστατικό και των στοιχείων των παρεχόμενων δικτύων ή υπηρεσιών, τα οποία έχουν επηρεαστεί.
. O πάροχος υποβάλλει στην ΑΔΑΕ την «Τελική Έκθεση Αναφοράς Περιστατικού Ασφάλειας», το αργότερο ένα μήνα μετά την υποβολή της Έκθεσης Αρχικής Αναφοράς, στην οποία καταγράφονται, κατ’ ελάχιστον, τα ακόλουθα:
[lowerroman]
.. Ημερομηνία και ώρα εκδήλωσης του περιστατικού.
.. Ημερομηνία και ώρα που έγινε αντιληπτό το περιστατικό.
.. Κατηγορία Δικτύου (π.χ. Σταθερό, Κινητό, Δορυφορικό) και Υπηρεσιών που επηρεάστηκαν [π.χ. Τηλεφωνία, Γραπτά μηνύματα (SMS), Πολυμεσικά μηνύματα (MMS), Περιήγηση στο Διαδίκτυο (Web Browsing)].
.. Αριθμός χρηστών που επηρεάστηκαν ανά υπηρεσία.
.. Χρονική διάρκεια περιστατικού.
.. Στοιχεία του Δικτύου που επηρεάστηκαν:
[arabic]
 ... είδος, όνομα κατασκευαστή, σύντομη περιγραφή της βασικής του λειτουργίας,
 ... κατηγορία του κόμβου (π.χ. πρωτεύον PoP, δευτερεύον PoP, ΑΚ),
 ... κατηγορία του δικτύου στο οποίο ανήκει (π.χ. επίπεδο πρόσβασης, συγκέντρωσης, άκρου δικτύου, διανομής, πυρήνα).
.. Πρωτεύουσα αιτία του περιστατικού (π.χ. ανθρώπινο λάθος, αστοχία υλικού ή λογισμικού, φυσικά φαινόμενα ή καταστροφές, κακόβουλη ενέργεια, ανεπάρκεια τρίτου μέρους ή εξωτερικού φορέα).
.. Δευτερεύουσα αιτία του περιστατικού.
.. Ενέργειες διαχείρισης και ανταπόκρισης στο περιστατικό.
.. Συλλεχθέντα στοιχεία για τη διερεύνηση του περιστατικού.
.. Διορθωτικά μέτρα και σχετικό χρονοδιάγραμμα.
.. Ενημέρωση θιγόμενων συνδρομητών ή άλλων ατόμων που επηρεάστηκαν από το περιστατικό και γνωστοποίηση στις αρμόδιες αρχές, σύμφωνα με την κείμενη νομοθεσία.
.. Ενδεχόμενες συστάσεις σε θιγόμενους συνδρομητές ή άλλα άτομα που επηρεάστηκαν από το περιστατικό, με σκοπό τον μετριασμό των αρνητικών επιπτώσεών του.
. Σε περίπτωση εν εξελίξει περιστατικού κατά τον χρόνο υποχρέωσης υποβολής της Τελικής Έκθεσης, ο πάροχος υποβάλλει Έκθεση Προόδου τη δεδομένη στιγμή και Τελική Έκθεση το αργότερο ένα μήνα μετά την υποβολή της Έκθεσης Προόδου.
Η Έκθεση Προόδου καταγράφει τα πεδία της «Τελικής Έκθεσης Αναφοράς Περιστατικού Ασφάλειας» που είναι γνωστά στον πάροχο τη δεδομένη στιγμή.
. Τυχόν πεδία της «Τελικής Έκθεσης Αναφοράς Περιστατικού Ασφάλειας» που είναι γνωστά στον πάροχο ήδη από το αρχικό στάδιο που γίνεται αντιληπτό το περιστατικό, συμπεριλαμβάνονται από τον πάροχο και στην «Έκθεση Αρχικής Αναφοράς Περιστατικού Ασφάλειας».

[heading=paragraph]
===== {empty}

H ΑΔΑΕ δύναται να ζητεί συμπληρωματικές πληροφορίες ή διευκρινίσεις σχετικά με τα περιστατικά ασφάλειας, πέραν των αναφερομένων στις εκθέσεις της παρ. 7.2.1 του παρόντος άρθρου.
Για τον λόγο αυτόν, οι πάροχοι διατηρούν όλες τις διαθέσιμες πληροφορίες σχετικά με τα περιστατικά ασφάλειας, για τα οποία έχουν υποβάλει Έκθεση Αναφοράς Περιστατικού Ασφάλειας, για διάστημα δύο (2) ετών από τον χρόνο υποβολής της Τελικής Έκθεσης Αναφοράς Συμβάντος Ασφάλειας, με την επιφύλαξη τήρησης της κείμενης νομοθεσίας περί προστασίας δεδομένων προσωπικού χαρακτήρα και τυχόν υποχρέωσης διατήρησής τους για μεγαλύτερο χρονικό διάστημα, εφόσον προβλέπεται από άλλες διατάξεις της κείμενης νομοθεσίας.

[heading=article]
=== Διαχείριση Παρακολούθησης και Ελέγχου

[heading=subarticle]
==== Διαδικασία Διαχείρισης Παρακολούθησης και Ελέγχου

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί και εφαρμόζει Διαδικασία Διαχείρισης Παρακολούθησης και Ελέγχου των ΠΕΣ, των υπηρεσιών/εφαρμογών τους και των εγκαταστάσεών τους, η οποία προβλέπει κατ’ ελάχιστον τις ακόλουθες ενέργειες:

. την οργάνωση του προσωπικού του παρόχου (ορισμός ρόλων και αρμοδιοτήτων) με σκοπό την αποτελεσματική εφαρμογή της εν λόγω διαδικασίας,
. την κατηγοριοποίηση των απαραίτητων συμβάντων και συναγερμών,
. την καταγραφή, διαχείριση και αξιολόγηση των συμβάντων και συναγερμών, με σκοπό τόσο τον προσδιορισμό κακόβουλων ενεργειών, σφαλμάτων και κενών ασφαλείας σε πραγματικό χρόνο όσο και τον εντοπισμό των περιστατικών ασφάλειας,
. την οργάνωση και κατηγοριοποίηση των ελέγχων εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών,
. την ενημέρωση του Υπεύθυνου Ασφάλειας Δικτύων και Υπηρεσιών και των αρμοδίων στελεχών του παρόχου.

[heading=paragraph]
===== {empty}

Ο πάροχος αξιολογεί και αναθεωρεί τη Διαδικασία Διαχείρισης Παρακολούθησης και Ελέγχου με βάση προηγούμενη εμπειρία του.

[heading=subarticle]
==== Παρακολούθηση Συμβάντων και Συναγερμών

[heading=paragraph]
===== {empty}

Ο πάροχος παρακολουθεί συνεχώς τα συμβάντα που λαμβάνουν χώρα στα ΠΕΣ, στις υπηρεσίες/εφαρμογές τους και στις εγκαταστάσεις τους αναφορικά με την ασφάλεια των δικτύων και υπηρεσιών, ώστε να εντοπίζονται εγκαίρως οι τυχόν κακόβουλες ενέργειες, σφάλματα ή κενά ασφάλειας.
Ανάλογα με το είδος, τη φύση και τη σοβαρότητα ενός συμβάντος ενεργοποιείται αντίστοιχος συναγερμός.
Ενδεικτικά, και όχι περιοριστικά, ως συμβάντα αναφέρονται:

[lowerroman]
. οι επανειλημμένες ανεπιτυχείς προσπάθειες πρόσβασης σε ΠΕΣ, υπηρεσίες/εφαρμογές και στους χώρους ή τις εγκαταστάσεις αυτών,
. πρόσβαση ή μεταβολή στη διαμόρφωση των ΠΕΣ και των υπηρεσιών/εφαρμογών τους που ενδέχεται να έχει σημαντική επίπτωση στην ασφάλεια του δικτύου,
. πρόσβαση ή μεταβολή σε ευαίσθητα αρχεία, όπως αρχεία που διατηρούν δικτυακά δεδομένα ή αρχεία εντολών για πρόσβαση σε δεδομένα επικοινωνίας συνδρομητών,
. αλλαγές στην κατάσταση και τη λειτουργία των ΠΕΣ και των υπηρεσιών/εφαρμογών τους, όπως η επανεκκίνηση ή η βίαιη διακοπή λειτουργίας τους,
. κάθε μη σύνηθες συμβάν που εντοπίζεται από τους μηχανισμούς ή τα συστήματα που αναφέρονται στην παρ. 5.3.1 του άρθρου 5 του παρόντος Κανονισμού.

[heading=paragraph]
===== {empty}

Για την παρακολούθηση των συμβάντων και των συναγερμών στα ΠΕΣ, ο πάροχος χρησιμοποιεί σύγχρονα συστήματα και λειτουργίες.
Στην κατηγορία αυτή εντάσσονται ενδεικτικά τα Κέντρα Λειτουργίας και Ασφάλειας Δικτύου (Network Operations Center - NOC, Security Operations Center - SOC), τα εργαλεία διαχείρισης πληροφοριών και συμβάντων ασφαλείας (Security Information and Event Management - SIEM), η παροχή αναφορών/συμβουλών από Ομάδες Αντιμετώπισης Συμβάντων της Ασφάλειας Υπολογιστών (Computer Security Incident Response Team - CSIRT) και άλλες δομές και υποστηρικτικά εργαλεία εντοπισμού δικτυακών και πληροφοριακών συμβάντων ή συναγερμών.

[heading=paragraph]
===== {empty}

Ανάλογα με την κρισιμότητα των συμβάντων και των συναγερμών, ο πάροχος ενεργοποιεί τη Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας της ενότητας 7.1 του άρθρου 7 του παρόντος Κανονισμού.

[heading=subarticle]
==== Διατήρηση Αρχείων Καταγραφής των ΠΕΣ και Όροι Διατήρησης Αρχείων

[heading=paragraph]
===== {empty}

Ο πάροχος τηρεί τα ακόλουθα αρχεία καταγραφής των ΠΕΣ:

. αρχείο καταγραφής των προσβάσεων στα ΠΕΣ, στο οποίο καταγράφονται, κατ’ ελάχιστον, το όνομα χρήστη που απέκτησε την πρόσβαση και η ημερομηνία και ώρα εκκίνησης και τερματισμού της πρόσβασης.
. αρχείο καταγραφής ενεργειών στο λειτουργικό σύστημα, στις βάσεις δεδομένων και στις εφαρμογές των ΠΕΣ.
Κάθε πρόσβαση σε δεδομένα επικοινωνίας των συνδρομητών ή χρηστών των παρεχόμενων δικτύων ή υπηρεσιών πρέπει επιπλέον να αιτιολογείται.
. αρχείο καταγραφής με τα συμβάντα και τους συναγερμούς των ΠΕΣ.

[heading=paragraph]
===== {empty}

Αναφορικά με τα αρχεία καταγραφής της παρ. 8.3.1 του παρόντος άρθρου:

. Ο πάροχος εξασφαλίζει ότι οι καταγραφές που περιλαμβάνονται στα αρχεία καταγραφής είναι πλήρεις και συνεχείς.
. Ο πάροχος διατηρεί Ειδικό Σχέδιο Αρχείων Καταγραφής, το οποίο, κατ’ ελάχιστον, περιλαμβάνει την αρχιτεκτονική και τις επιμέρους μεθόδους δημιουργίας, συλλογής, αποθήκευσης και διαχείρισης των αρχείων καταγραφής, πλήρη περιγραφή του περιεχομένου αυτών, καθώς και τις τεχνικές διασφάλισης της ακεραιότητας, της εμπιστευτικότητας, της διαθεσιμότητας και της χρονοσήμανσης (timestamp) των καταγραφών.
. Σε περίπτωση διακοπής των καταγραφών που προβλέπονται στα αρχεία καταγραφής, καθώς και σε περίπτωση περιστατικού παραβίασης της ακεραιότητας, εμπιστευτικότητας, διαθεσιμότητας και χρονοσήμανσης των καταγραφών, ο πάροχος ενεργοποιεί αμελλητί τη Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας της ενότητας 7.1 του άρθρου 7 του παρόντος Κανονισμού.

[heading=paragraph]
===== {empty}

Με τα άρθρα 3 έως και 9 του παρόντος Κανονισμού ορίζεται υποχρέωση διατήρησης αρχείων για τον σκοπό του ελέγχου της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών.
Με την επιφύλαξη των διατάξεων της κείμενης νομοθεσίας περί προστασίας δεδομένων προσωπικού χαρακτήρα, των ν. 3471/2006 (Α’ 133), ν. 3783/2009 (Α'136), ν. 3917/2011 (Α'22), και της τήρησης υποχρεώσεων που τυχόν απορρέουν από άλλες διατάξεις της κείμενης νομοθεσίας, ο πάροχος διατηρεί τα εν λόγω αρχεία για χρονικό διάστημα τουλάχιστον δύο (2) ετών, λαμβάνοντας τα κατάλληλα μέτρα για τη διασφάλιση της ακεραιότητας, της εμπιστευτικότητας και της διαθεσιμότητάς τους.
Ειδικά ως προς τα συστήματα για την άρση του απορρήτου των επικοινωνιών (συστήματα νόμιμης επισύνδεσης και διατήρησης δεδομένων), ο πάροχος διατηρεί τα αρχεία καταγραφής της παρ. 8.3.1 του παρόντος άρθρου για χρονικό διάστημα τουλάχιστον δέκα (10) ετών.
Σε περίπτωση που βρίσκεται σε εξέλιξη έλεγχος της ΑΔΑΕ, ο πάροχος διατηρεί τα αρχεία της παρούσας παραγράφου ακόμα και μετά το πέρας του κατά τα ως άνω προβλεπόμενου χρόνου διατήρησης και προβαίνει στη διαγραφή τους μόνο κατόπιν σχετικής απόφασης της ΑΔΑΕ.

[heading=subarticle]
==== Εσωτερικός Έλεγχος Εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών

[heading=paragraph]
===== {empty}

Ο πάροχος προβαίνει σε προγραμματισμό εσωτερικού ελέγχου εφαρμογής της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών, με σκοπό την ορθή τήρηση των απαιτήσεων αυτής και τη διαπίστωση της επάρκειας και αποτελεσματικότητας των μηχανισμών ασφάλειας.
Ο εσωτερικός έλεγχος βασίζεται σε διεθνείς, βέλτιστες πρακτικές, καταγράφεται σε αρχείο, καλύπτει όλο το εύρος εφαρμογής της Πολιτικής και πραγματοποιείται κατ’ ελάχιστον ανά δύο (2) έτη.

[heading=paragraph]
===== {empty}

Ο εσωτερικός έλεγχος περιλαμβάνει τη χρήση και την εξέταση των αρχείων καταγραφής της παρ. 8.3.1 του παρόντος άρθρου, κατά περίπτωση σε συσχετισμό με άλλα αρχεία που προβλέπονται στον παρόντα Κανονισμό.
Επιπλέον, ο εσωτερικός έλεγχος περιλαμβάνει τεχνικούς ελέγχους διείσδυσης (penetration tests) στα ΠΕΣ.

[heading=paragraph]
===== {empty}

Ο εσωτερικός έλεγχος είναι δυνατό να πραγματοποιείται από εξωτερικό φορέα ή από ειδικά εξουσιοδοτημένους προς τούτο, εργαζόμενους του παρόχου, λαμβάνοντας υπόψη τις αρχές της αντικειμενικότητας και της αμεροληψίας.
Σε κάθε περίπτωση, λαμβάνεται μέριμνα από τον πάροχο αναφορικά με ζητήματα τήρησης της εμπιστευτικότητας και μη διαρροής πληροφοριών και δεδομένων.

[heading=paragraph]
===== Διαδικασία Εσωτερικού Ελέγχου

[heading=paragraph]
====== {empty}

Ο εσωτερικός έλεγχος εφαρμογής της Πολιτικής περιλαμβάνει τα ακόλουθα στάδια: α) την προετοιμασία του ελέγχου, β) τη διεξαγωγή του ελέγχου και γ) τα αποτελέσματα του ελέγχου.
O πάροχος διατηρεί σε αρχείο την τεκμηρίωση για κάθε στάδιο του ελέγχου, ακόμη και στην περίπτωση που δεν υπάρχουν ευρήματα από τον έλεγχο.

[heading=paragraph]
====== {empty}

Κατά το στάδιο της προετοιμασίας του εσωτερικού ελέγχου, ο πάροχος καθορίζει τα συστήματα και τις διαδικασίες/μηχανισμούς που θα ελεγχθούν, το χρονοδιάγραμμα και τον ορισμό των προσώπων που απαρτίζουν την Ομάδα Εσωτερικού Ελέγχου.

[heading=paragraph]
====== {empty}

Κατά το στάδιο της διεξαγωγής του εσωτερικού ελέγχου, η απόδοση σε ένα ή περισσότερα μέλη της Ομάδας Εσωτερικού Ελέγχου δικαιωμάτων πρόσβασης σε εργαλεία λογισμικού, συστήματα ή χώρους των εγκαταστάσεων επιτρέπεται μόνο για το χρονικό διάστημα του αντίστοιχου εσωτερικού ελέγχου και πραγματοποιείται σύμφωνα με την Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών του παρόχου.

[heading=paragraph]
====== {empty}

Σε περίπτωση που προκύψουν ευρήματα από τον εσωτερικό έλεγχο, ο πάροχος ορίζει τις απαιτούμενες ενέργειες (όπως, ενδεικτικά, αναθεώρηση διαδικασιών/οδηγιών, επικαιροποίηση λογισμικού, τροποποίηση παραμέτρων τεχνικής διαμόρφωσης, μερική ή ολική αντικατάσταση συστήματος ή εφαρμογής), το χρονοδιάγραμμα πραγματοποίησής τους, τις αρμοδιότητες των εργαζομένων ή των συνεργατών του για την πραγματοποίηση των διορθωτικών ενεργειών και τα πρόσωπα που θα είναι ειδικά εξουσιοδοτημένα να ελέγχουν την ορθή υλοποίηση των ενεργειών της παρούσας παραγράφου.

[heading=paragraph]
====== {empty}

Ανάλογα με τη φύση και την κρισιμότητα των ευρημάτων του εσωτερικού ελέγχου, ο πάροχος ενεργοποιεί τη Διαδικασία Διαχείρισης Περιστατικών Ασφάλειας της ενότητας 7.1 του άρθρου 7 του παρόντος Κανονισμού.

[heading=article]
=== Ευαισθητοποίηση σε Θέματα Απειλών και Ενημέρωση Χρηστών/Συνδρομητών

[heading=subarticle]
==== Συλλογή και Διαχείριση Πληροφοριών για Απειλές

[heading=paragraph]
===== {empty}

Ο πάροχος διατηρεί και εφαρμόζει Διαδικασία για την Παρακολούθηση, Συλλογή και Διαχείριση πληροφοριών σχετικά με πιθανές απειλές ασφάλειας του δικτύου και των υπηρεσιών του, η οποία περιλαμβάνει κατ’ ελάχιστον τα παρακάτω:

[heading=paragraph]
====== {empty}

Ο πάροχος παρακολουθεί τακτικά πληροφορίες και στοιχεία ανάλυσης απειλών (threat intelligence) από σχετικές, τρέχουσες και αξιόπιστες εξωτερικές πηγές πληροφόρησης, όπως ενδεικτικά πληροφορίες διαθέσιμες στο ευρύ κοινό, πληροφορίες ασφαλείας ανοιχτής πηγής, εκθέσεις ανάλυσης απειλών από εμπορικούς φορείς, κατασκευαστές εξοπλισμού και λογισμικού και ακαδημαϊκούς και ερευνητικούς φορείς, καθώς και άτυπες και περιστασιακές κοινοποιήσεις στοιχείων ανάλυσης απειλών από σχετικούς οργανισμούς και φορείς στη βάση διμερών σχέσεων.

[heading=paragraph]
====== {empty}

Ο πάροχος αναλύει, αξιολογεί, συσχετίζει και χαρακτηρίζει τις συλλεχθείσες πληροφορίες για απειλές.

[heading=paragraph]
====== {empty}

Ο πάροχος ορίζει τους τρόπους λήψης απόφασης, καθώς και τις συνθήκες κατά τις οποίες ενεργοποιούνται τα μέτρα για την ελαχιστοποίηση και τον περιορισμό των συνεπειών/επιπτώσεων από απειλές ασφάλειας του δικτύου και των υπηρεσιών του.

[heading=paragraph]
====== {empty}

Ο πάροχος ορίζει τους τρόπους διάχυσης και κοινοποίησης των πληροφοριών και στοιχείων ανάλυσης απειλών σε συνεργασία με σχετικούς οργανισμούς και φορείς στη βάση διμερών σχέσεων, καθώς και τους κανόνες σήμανσης ευαίσθητων πληροφοριών περί απειλών ασφάλειας για την απλούστευση κοινοποίησης και διάδοσης των πληροφοριών περί απειλών.

[heading=subarticle]
==== Ευαισθητοποίηση και Ενημέρωση Χρηστών/Συνδρομητών

[heading=paragraph]
===== {empty}

Ο πάροχος ενημερώνει τους συνδρομητές ή χρήστες των παρεχόμενων δικτύων ή υπηρεσιών τουλάχιστον κατά τη σύναψη της μεταξύ τους σύμβασης, αλλά και σε τακτά χρονικά διαστήματα, με κάθε πρόσφορο τρόπο, σχετικά με τα μέτρα που ενδείκνυται να λαμβάνουν για την ασφάλεια των επικοινωνιών τους, ιδίως σχετικά με τους κανόνες ενδεδειγμένης χρήσης για την προστασία των κωδικών πρόσβασης που κατέχουν, τους κανόνες ορθής χρήσης των παρεχόμενων δικτύων ή υπηρεσιών, αλλά και τους τρόπους χρήσης τεχνολογιών και πόρων σχετικών με την ασφάλεια των πληροφοριών.

[heading=paragraph]
===== {empty}

Ο πάροχος ενημερώνει τους συνδρομητές ή χρήστες των παρεχόμενων δικτύων ή υπηρεσιών για συγκεκριμένες και σημαντικές απειλές που ενδέχεται να τους επηρεάσουν, σύμφωνα με την κείμενη νομοθεσία.
Η ενημέρωση αυτή δύναται να παρέχεται μέσω τακτικών ή/και έκτακτων δελτίων ασφαλείας που εκδίδει ο πάροχος, μέσω του ιστοτόπου του με αποκλειστικό θέμα τις απειλές ασφαλείας ή μέσω οποιουδήποτε ευρέως χρησιμοποιούμενου τρόπου παροχής της σχετικής πληροφόρησης.

[heading=part]
== Έλεγχος, Υποχρεώσεις Παρόχων, Μεταβατικές και Τελικές Διατάξεις

[heading=article]
=== Διαδικασία Ελέγχου από την ΑΔΑΕ

[heading=paragraph]
==== {empty}

Η ΑΔΑΕ διενεργεί τακτικούς ελέγχους περιοδικά στους παρόχους, προκειμένου να διαπιστώσει τη συμμόρφωση της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών τους με τον παρόντα Κανονισμό.
Επίσης, η ΑΔΑΕ, στο πλαίσιο των αρμοδιοτήτων της, διενεργεί έκτακτους ελέγχους στους παρόχους, αυτεπαγγέλτως ή κατόπιν καταγγελίας ή περιστατικού ασφάλειας.

[heading=paragraph]
==== {empty}

Ο έλεγχος διενεργείται από την ΑΔΑΕ με την παρουσία του Υπεύθυνου Ασφάλειας Δικτύων και Υπηρεσιών, όπως αυτός προβλέπεται στην παρ. 3.3.2. του άρθρου 3 του παρόντος Κανονισμού, ή άλλου εξουσιοδοτημένου προς τούτο εργαζόμενου του παρόχου, σύμφωνα με τα ακολούθως οριζόμενα:

[heading=paragraph]
===== {empty}

Η ΑΔΑΕ, σύμφωνα με το άρθρο 6 του ν. 3115/2003, με απόφασή της, ορίζει ομάδα ελέγχου, με σκοπό τον έλεγχο συγκεκριμένου παρόχου.
Με την ίδια απόφαση καθορίζεται η ειδικότερη σύνθεση της ομάδας ελέγχου.

[heading=paragraph]
===== {empty}

Ο τακτικός έλεγχος διενεργείται με επιτόπια επίσκεψη στις εγκαταστάσεις του παρόχου και συμπληρωματική αλληλογραφία όπου κρίνεται απαραίτητο.
Η ομάδα ελέγχου ενημερώνει εγγράφως τον Υπεύθυνο Ασφάλειας Δικτύων και Υπηρεσιών για την ημερομηνία διενέργειας του ελέγχου, ζητώντας του παράλληλα να έχει διαθέσιμα πλήρη αντίγραφα των υφισταμένων διαδικασιών που υλοποιούν την Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών, από τα οποία να προκύπτει σαφώς η ημερομηνία έκδοσής τους.
Η ομάδα ελέγχου ζητά, κατά την κρίση της, τα απαραίτητα στοιχεία και συνεργάζεται με το προσωπικό του ελεγχόμενου προσώπου.

[heading=paragraph]
===== {empty}

Ο έκτακτος έλεγχος διενεργείται χωρίς την προηγούμενη ενημέρωση του παρόχου σχετικά με το αντικείμενο του ελέγχου και διεξάγεται με επιτόπια επίσκεψη στις εγκαταστάσεις του παρόχου και συμπληρωματική αλληλογραφία, όπου κρίνεται απαραίτητο.
Σε περίπτωση διενέργειας του ελέγχου με άλλο τρόπο, απαιτείται ειδική αιτιολόγηση.

[heading=paragraph]
===== {empty}

Από τη λήψη της έγγραφης ενημέρωσης του Υπεύθυνου Ασφάλειας Δικτύων και Υπηρεσιών περί της διεξαγωγής τακτικού ελέγχου από την ΑΔΑΕ και εν γένει από την έναρξη κάθε είδους ελέγχου και μέχρι να λάβει έγγραφη ενημέρωση από την Αρχή αναφορικά με το πέρας του ελέγχου, ο πάροχος δεν δύναται να προβεί σε οποιαδήποτε αναθεώρηση του κειμένου της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών ή των συνοδευτικών αρχείων αυτής (διαδικασίες, τεχνικές οδηγίες κ.ά.).

[heading=paragraph]
===== {empty}

Για κάθε επιτόπιο έλεγχο συντάσσεται ειδικό έγγραφο με τίτλο «Πρακτικό Διενέργειας Επιτόπιου Ελέγχου στις εγκαταστάσεις του παρόχου», το οποίο συνυπογράφεται από τον Υπεύθυνο Ασφάλειας Δικτύων και Υπηρεσιών ή τον εξουσιοδοτημένο προς τούτο εργαζόμενο του παρόχου που συνέπραξε στον επιτόπιο έλεγχο καθώς και την ομάδα ελέγχου της ΑΔΑΕ.

[heading=paragraph]
==== {empty}

Μετά την ολοκλήρωση όλων των αναγκαίων επιμέρους ελέγχων, η ομάδα ελέγχου εξετάζει διεξοδικά το σύνολο των συλλεχθέντων στοιχείων και συντάσσει ειδικό έγγραφο με τίτλο «Έκθεση διενέργειας τακτικού/εκτάκτου ελέγχου στον πάροχο», το οποίο περιλαμβάνει απαραιτήτως τα ακόλουθα στοιχεία:

. Τα στοιχεία της απόφασης της ΑΔΑΕ με την οποία αποφασίστηκε η διενέργεια του ελέγχου,
. Το ονοματεπώνυμο και την ιδιότητα των προσώπων που απαρτίζουν την ομάδα ελέγχου και την ημερομηνία σύστασης της τελευταίας,
. Την επωνυμία του ελεγχόμενου παρόχου, καθώς και το όνομα του Υπευθύνου Ασφάλειας Δικτύων και Υπηρεσιών,
. Τα Πρακτικά Διενέργειας Επιτόπιων Ελέγχων στις εγκαταστάσεις του ελεγχόμενου παρόχου, με αναγραφή των συγκεκριμένων ημερομηνιών που αυτοί έλαβαν χώρα, καθώς και κάθε σχετική έγγραφη επικοινωνία μεταξύ της ΑΔΑΕ και του παρόχου στο πλαίσιο της διεξαγωγής του ελέγχου,
. Αναλυτική περιγραφή των ευρημάτων του ελέγχου και διαπίστωση τυχόν παραλείψεων ή αναντιστοιχιών με τον παρόντα Κανονισμό και την κείμενη νομοθεσία, καθώς και την Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών,
. Καταγραφή παρατηρήσεων αναφορικά με την εφαρμογή της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών.
. Τελικό πόρισμα του ελέγχου.

[heading=paragraph]
==== {empty}

Η απόφαση της Ολομέλειας της ΑΔΑΕ για την έγκριση της «Έκθεσης διενέργειας ελέγχου στον πάροχο», μετά της συνημμένης σε αυτήν έκθεσης, γνωστοποιείται στον ελεγχόμενο πάροχο.

[heading=paragraph]
==== {empty}

Κατά τα λοιπά ισχύουν οι διατάξεις του ν. 3115/2003 «Αρχή Διασφάλισης του Απορρήτου των Επικοινωνιών» (Α'47).

[heading=article]
=== Υποχρέωση Ενημέρωσης της ΑΔΑΕ

[heading=paragraph]
==== {empty}

Οι πάροχοι που λειτουργούν υπό καθεστώς Γενικής Άδειας, όπως αυτό καθορίζεται από την εκάστοτε ισχύουσα νομοθεσία, υποχρεούνται εντός προθεσμίας δύο (2) μηνών από τη δημοσίευση του παρόντος στην Εφημερίδα της Κυβερνήσεως, να δηλώσουν προς την ΑΔΑΕ με υπεύθυνη δήλωση του νόμιμου εκπροσώπου τους:

. Τις δραστηριότητες για τις οποίες έχουν υποβάλει Δήλωση Καταχώρησης στην ΕΕΤΤ για τη λειτουργία υπό καθεστώς Γενικής Αδείας.
. εάν ασκούν εν τοις πράγμασι τις δραστηριότητες για τις οποίες έχουν υποβάλει Δήλωση Καταχώρησης στην ΕΕΤΤ, περιγράφοντας αναλυτικά τις ασκούμενες δραστηριότητες και τα είδη των ΠΕΣ για την άσκηση αυτών των δραστηριοτήτων.
. εάν δεν ασκούν εν τοις πράγμασι τις δραστηριότητες για τις οποίες έχουν υποβάλει Δήλωση Καταχώρησης στην ΕΕΤΤ, επισημαίνοντας εάν τις έχουν ασκήσει στο παρελθόν και για ποιο χρονικό διάστημα.
. τα στοιχεία του Υπεύθυνου Ασφάλειας Δικτύων και Υπηρεσιών, σύμφωνα με τα διαλαμβανόμενα στη παρ. 3.3.2 του άρθρου 3 του παρόντος Κανονισμού.

[heading=paragraph]
==== {empty}

Οι πάροχοι που υποβάλλουν δήλωση καταχώρησης στην ΕΕΤΤ υπό καθεστώς Γενικής Αδείας μετά την έναρξη ισχύος του παρόντος Κανονισμού, υποχρεούνται να υποβάλουν τη δήλωση του άρθρου 11.1 εντός προθεσμίας δύο (2) μηνών από την έναρξη των αντίστοιχων δραστηριοτήτων.

[heading=paragraph]
==== {empty}

Οι πάροχοι των παρ. 11.1 και 11.2, ανεξαρτήτως της υποβολής αντίστοιχης Δήλωσης Καταχώρησης στην ΕΕΤΤ, οφείλουν να ενημερώνουν αμελλητί την ΑΔΑΕ σε περίπτωση που επέλθει οποιαδήποτε μεταβολή ως προς τις δηλωθείσες δραστηριότητές τους που ασκούν εν τοις πράγμασι, καθώς και στην περίπτωση που επέλθει μεταβολή στην εταιρική μορφή, στην επωνυμία και στην έδρα τους.

[heading=article]
=== Υποβολή και Υλοποίηση Πολιτικής Ασφάλειας

[heading=paragraph]
==== {empty}

Οι πάροχοι που ασκούν εν τοις πράγμασι τις δραστηριότητες του άρθρου 1.1 οφείλουν να συντάξουν στην ελληνική γλώσσα και να υλοποιήσουν την Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών, εντός προθεσμίας εννέα (9) μηνών από τη δημοσίευση του παρόντος στην Εφημερίδα της Κυβερνήσεως ή εντός προθεσμίας δώδεκα (12) μηνών από την έναρξη ή μεταβολή των αντίστοιχων δραστηριοτήτων τους.

[heading=paragraph]
==== {empty}

Ειδικότερα, οι πάροχοι που υπάγονται στο πεδίο εφαρμογής του ν. 3674/2008, όπως ισχύει, υποχρεούνται να υποβάλουν στην ΑΔΑΕ προς έγκριση Πολιτική Ασφάλειας Δικτύων και Υπηρεσιών, στην ελληνική γλώσσα, εντός προθεσμίας τριών (3) μηνών από τη δημοσίευση του παρόντος στην Εφημερίδα της Κυβερνήσεως, ή εντός προθεσμίας έξι (6) μηνών από την έναρξη ή μεταβολή των αντίστοιχων δραστηριοτήτων τους, ή σε περίπτωση αναθεώρηση αυτής, όποτε αυτή λαμβάνει χώρα.
Στην ως άνω υποχρέωση εμπίπτουν οι πάροχοι που παρέχουν ιδίως τις ακόλουθες υπηρεσίες, σύμφωνα με τον Γενικό Κανονισμό της ΕΕΤΤ όπως εκάστοτε ισχύει:

. S001: Σταθερές υπηρεσίες διαπροσωπικών επικοινωνιών βάσει αριθμών
. S002: Κινητές υπηρεσίες διαπροσωπικών επικοινωνιών βάσει αριθμών

Οι πάροχοι της παρούσας παραγράφου υποχρεούνται εντός προθεσμίας έξι (6) μηνών από τη γνωστοποίηση σε αυτούς της απόφασης της ΑΔΑΕ περί έγκρισης της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών να την υλοποιήσουν και να ενημερώσουν εγγράφως την ΑΔΑΕ.
Σε περίπτωση υποβολής αναθεωρημένης Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών, ο χρόνος υλοποίησής της θα ορίζεται κατά περίπτωση από την ΑΔΑΕ και θα γνωστοποιείται στον πάροχο με την απόφαση περί έγκρισης της Πολιτικής Ασφάλειας Δικτύων και Υπηρεσιών.

[heading=paragraph]
==== {empty}

Οι πάροχοι δεν υποβάλλουν στην ΑΔΑΕ προς έγκριση τις διαδικασίες ασφάλειας που προβλέπονται στο πλαίσιο του παρόντος Κανονισμού.

[heading=paragraph]
==== {empty}

Σε περίπτωση που παρέλθει άπρακτη η προθεσμία εντός της οποίας οι πάροχοι της παρ. 12.1 του παρόντος οφείλουν να συντάξουν και να υλοποιήσουν την Πολιτική Ασφαλείας εφαρμόζονται οι κυρώσεις του ν. 3115/2003, όπως ισχύει.
Σε περίπτωση που παρέλθει άπρακτη η προθεσμία εντός της οποίας οι πάροχοι της παρ. 12.2 του παρόντος οφείλουν να υποβάλουν προς έγκριση την Πολιτική Ασφαλείας τους και να την υλοποιήσουν επιβάλλονται οι κυρώσεις του ν. 3674/2008, όπως ισχύει.

[heading=article,type=transitional-provisions]
=== Μεταβατικές διατάξεις

[heading=paragraph]
==== {empty}

Κατά το χρονικό διάστημα από τη δημοσίευση του παρόντος μέχρι την ημερομηνία υλοποίησης των Πολιτικών Ασφαλείας των παρόχων της παρ. 12.1 και 12.2 του παρόντος οι εν λόγω πάροχοι υποχρεούνται στην τήρηση της προστασίας του απορρήτου των επικοινωνιών, σύμφωνα με την κείμενη νομοθεσία και στη διασφάλιση του ελέγχου που διενεργείται από την ΑΔΑΕ σχετικά με την προστασία του απορρήτου των επικοινωνιών, διατηρώντας τα μέτρα και τις βέλτιστες πρακτικές που έχουν ήδη προβλεφθεί για τον σκοπό αυτό.
Μετά τη λήξη των οριζόμενων προθεσμιών για τους παρόχους της παρ. 12.1 του παρόντος, καθώς και μετά τη λήξη των οριζόμενων προθεσμιών για τους παρόχους της παρ. 12.2, και εφόσον αυτοί δεν έχουν υποβάλει Πολιτική Ασφαλείας στην ΑΔΑΕ προς έγκριση εντός της νόμιμης προθεσμίας, ισχύουν τα μέτρα και οι υποχρεώσεις του παρόντος.

[heading=paragraph]
==== {empty}

Οι πάροχοι που έχουν αποστείλει στην ΑΔΑΕ ενημέρωση σχετικά με τις δραστηριότητες για τις οποίες έχουν υποβάλει Δήλωση Καταχώρησης στην ΕΕΤΤ για τη λειτουργία υπό καθεστώς Γενικής Αδείας, δεν υποχρεούνται να υποβάλουν εκ νέου ενημέρωση, σύμφωνα με τα οριζόμενα στο άρθρο 11 του παρόντος, εφόσον δεν έχουν υπάρξει μεταβολές των στοιχείων των περ. α-δ της παρ. 11.1 του άρθρου 11 του παρόντος Κανονισμού, καθώς και μεταβολές στην εταιρική μορφή, στην επωνυμία και στην έδρα τους.

[heading=article,type=entry-into-force]
=== Καταργούμενες διατάξεις -- Έναρξη ισχύος

Οι υπ' αρ. 165/2011 και 28/2024 αποφάσεις της ΑΔΑΕ, καθώς και οι Πολιτικές Ασφαλείας που είχαν εγκριθεί βάσει αυτών καταργούνται από την έναρξη ισχύος του παρόντος.
Η ισχύς του παρόντος Κανονισμού αρχίζει με τη δημοσίευσή του στην Εφημερίδα της Κυβερνήσεως.

Ο παρών Κανονισμός να δημοσιευθεί στην Εφημερίδα της Κυβερνήσεως.

[.colophon]
== Υπογραφές

[align=right]
Μαρούσι, 31 Ιουλίου 2025 +
Ο Αντιπρόεδρος +
ΓΕΩΡΓΙΟΣ ΜΠΑΚΑΛΗΣ