= Τροποποίηση διατάξεων Κώδικα Φορολογίας Εισοδήματος και άλλες διατάξεις
:docnumber: 4330
:doctype: act
:copyright-year: 2015
:published-date: 2015-06-16
:language: el
:script: Grek
:fek-number: 59
:fek-series: Α'
:fek-year: 2015
:publisher: ΕΘΝΙΚΟ ΤΥΠΟΓΡΑΦΕΙΟ
:mn-document-class: lawgr

[.preface]
== {empty}

Ο ΠΡΟΕΔΡΟΣ ΤΗΣ ΕΛΛΗΝΙΚΗΣ ΔΗΜΟΚΡΑΤΙΑΣ

Εκδίδομε τον ακόλουθο νόμο που ψήφισε η Βουλή:

[heading=article]
== Τροποποίηση διατάξεων Κώδικα Φορολογίας Εισοδήματος (κύρωση με το Ν. 4172/2013, Α ́ 167)

[heading=paragraph]
=== {empty}

Η περίπτωση η ́ του άρθρου 33 του Κώδικα Φορολογίας Εισοδήματος (Κ.Φ.Ε.) αντικαθίσταται ως εξής:

«η) Προκειμένου για αντικειμενικές δαπάνες και υπηρεσίες του άρθρου 31 φυσικού προσώπου που έχει τη 
φορολογική κατοικία του στην αλλοδαπή. Προκειμένου για δαπάνες απόκτησης περιουσιακών στοιχείων του 
άρθρου 32 φυσικού προσώπου που έχει τη φορολογική κατοικία του στην αλλοδαπή εφόσον δεν αποκτά εισόδημα στην Ελλάδα.»

[heading=paragraph]
=== {empty}

Στο τέλος της περίπτωσης α ́ της παρ. 1 του άρθρου 34 του Κ.Φ.Ε. προστίθεται η φράση:

«έχει εισόδημα μόνο από κεφάλαιο ή/και από υπεραξία μεταβίβασης κεφαλαίου και το τεκμαρτό του εισόδημα δεν υπερβαίνει το 
ποσό των εννιά χιλιάδων πεντακοσίων (9.500) ευρώ ή».

[heading=paragraph]
=== {empty}

Η περίπτωση ε ́ της παρ. 1 του άρθρου 34 του Κ.Φ.Ε. καταργείται.

[heading=paragraph]
=== {empty}

Στο άρθρο 72 του Ν. 4172/2013 προστίθεται νέα παράγραφος 35 ως εξής:

«35. Όταν το πραγματικό εισόδημα των φορολογουμένων κατά το φορολογικό έτος 2014 δεν υπερβαίνει το 
ποσό των 6.000 ευρώ και το τεκμαρτό τους εισόδημα δεν υπερβαίνει το ποσό των 9.500 ευρώ και εφόσον 
δεν ασκείται επιχειρηματική δραστηριότητα για την οποία απαιτείται η υποβολή δήλωση έναρξης εργασιών 
ή ατομική αγροτική δραστηριότητα, το εισόδημα αυτό, εξαιρουμένου του εισοδήματος από κεφάλαιο και από 
υπεραξία μεταβίβασης κεφαλαίου, και η προστιθέμενη διαφορά τεκμηρίων, φορολογούνται με την κλίμακα των 
μισθωτών – συνταξιούχων της παρ. 1 του άρθρου 15. Εάν το πραγματικό εισόδημα της προηγούμενης παραγράφου
υπερβαίνει το ποσό των 6.000 ευρώ, το υπερβάλλον ποσό φορολογείται με την κλίμακα της επιχειρηματικής 
δραστηριότητας. Οι διατάξεις του παρόντος άρθρου εφαρμόζονται και για τους φορολογούμενους που διέκοψαν
την επιχειρηματική τους δραστηριότητα, για το εισόδημα που απέκτησαν μετά τη διακοπή της.»

[heading=paragraph]
=== {empty}

Στο τέλος της παρ. 2 του άρθρου 39 του Ν. 4172/2013 προστίθεται νέο εδάφιο ως εξής:

«Ειδικά για τους ασκούντες ατομική αγροτική επιχειρηματική δραστηριότητα δεν υπολογίζεται τεκμαρτό 
εισόδημα από ιδιοχρησιμοποίηση ή δωρεάν παραχώρηση προς ανιόντες, κατιόντες και συζύγους, αγροτικών 
εκτάσεων στις οποίες περιλαμβάνονται λιβάδια, καλλιεργήσιμες γαίες, βοσκήσιμες γαίες, και κάθε είδους 
κατασκευές ή εγκαταστάσεις που χρησιμοποιούνται για την άσκηση της δραστηριότητας αυτής.»

[heading=paragraph]
=== {empty}

Οι διατάξεις της παραγράφων 1, 2 και 5 του παρόντος άρθρου έχουν εφαρμογή για το φορολογικό έτος 
2014 και εξής.

[heading=article]
== Υπόχρεος για την απόδοση του Φόρου Προστιθέμενης Αξίας για την κατασκευή αγωγών φυσικού αερίου

[heading=paragraph]
=== {empty}

Στο άρθρο 35 παρ. 1 του Κώδικα Φόρου Προστιθέμενης Αξίας (Φ.Π.Α., Ν. 2859/2000) προστίθεται νέα περίπτωση κ ́ ως εξής:

«κ) ο εγκατεστημένος στο εσωτερικό της χώρας, υποκείμενος στο φόρο με δραστηριότητα μεταφοράς 
φυσικού αερίου μέσω αγωγών για τα αγαθά και τις υπηρεσίες, που αποκλειστικά χρησιμοποιεί για την κατασκευή των αγωγών αυτών.»

[heading=article]
== Απαλλαγή χρηματικών δωρεών από το φόρο

[heading=paragraph]
=== {empty}

Στην ενότητα Γ ́ του άρθρου 43 του Κώδικα διατάξεων φορολογίας κληρονομιών, δωρεών, γονικών παροχών 
και κερδών από τυχερά παίγνια, ο οποίος κυρώθηκε με το πρώτο άρθρο του Ν. 2961/2001 (Α ́ 266), όπως ισχύει, 
προστίθεται περίπτωση στ ́ ως ακολούθως:

«στ) χρηματικά ποσά που καταβάλλονται από την 1η Ιανουαρίου 2015 έως τις 31 Δεκεμβρίου 2015 σε σύζυγο, 
τέκνα, γονείς και αδέλφια των προσώπων που απεβίωσαν ή αγνοούνται λόγω του ναυαγίου του πλοίου 
Norman Atlantic, που έλαβε χώρα το Δεκέμβριο του 2014.»

[heading=article]
== Επαναπροσδιορισμός των καθαρών κερδών για τα πρατήρια καπνοβιομηχανικών προϊόντων

[heading=paragraph]
=== {empty}

Για τον προσδιορισμό των καθαρών κερδών χρήσης 2004 των επιχειρήσεων που επανεντάχθηκαν στη Β ́ 
κατηγορία βιβλίων του Κώδικα Βιβλίων και Στοιχείων (Π.δ. 186/1992, Α ́ 84) με τη διάταξη του άρθρου 32 παρ. 4 
του Ν. 3229/2004 (Α ́ 38) η απογραφή της χρήσης αυτής υπολογίζεται σύμφωνα με τη διάταξη της παρ. 1 
περίπτωση γ ́ του άρθρου 31 του Ν. 2238/1994 (Α ́ 151) και γίνεται επαναπροσδιορισμός των καθαρών κερδών 
και νέα εκκαθάριση του φόρου εισοδήματος από την αρμόδια Δημόσια Οικονομική Υπηρεσία.

[heading=article]
== Υποχρεώσεις τρίτων για τον Ενιαίο Φόρο Ιδιοκτησίας Ακινήτων

[heading=paragraph]
=== {empty}

Η παρ. 1 του άρθρου 54Α του Ν. 4174/2013 αντικαθίσταται ως ακολούθως:

«1. Απαγορεύεται κάθε υποσχετική ή εκποιητική δικαιοπραξία με την οποία συστήνονται, μεταβάλλονται, 
αλλοιώνονται ή μεταβιβάζονται, από οποιαδήποτε αιτία δικαιώματα επί ακινήτου ή παρέχεται δικαίωμα προσημείωσης
ή υποθήκης σε αυτό, αν δεν μνημονεύεται και δεν επισυνάπτεται από το συμβολαιογράφο στο συμβόλαιο
που συντάσσει, πιστοποιητικό της Φορολογικής Διοίκησης, με το οποίο πιστοποιείται ότι το ίδιο ακίνητο 
περιλαμβάνεται στη δήλωση Ενιαίου Φόρου Ιδιοκτησίας Ακινήτων, καθώς και ότι ο φορολογούμενος έχει 
καταβάλει, ή νόμιμα απαλλαγεί από τον ΕΝ.Φ.Ι.Α. για το συγκεκριμένο ακίνητο και έχει καταβάλει τις ληξιπρόθεσμες
δόσεις, έχει ρυθμίσει ή έχει νόμιμα απαλλαγεί από τον ΕΝ.Φ.Ι.Α. για τα υπόλοιπα ακίνητα, για τα οποία 
είναι υπόχρεος για τα πέντε (5) προηγούμενα έτη. Τα παραπάνω ισχύουν και για τη σύνταξη περίληψης κατακυρωτικής
έκθεσης επί εκούσιου πλειστηριασμού. Στην περίπτωση αυτή το πιστοποιητικό προσκομίζεται μόνον 
από τον επισπεύδοντα τον εκούσιο πλειστηριασμό. Ειδικά κατά το έτος 2015, το πιστοποιητικό χορηγείται 
για τα έτη 2011, 2012, 2013 και 2014.

Δεν απαιτείται η μνημόνευση, επισύναψη ή προσκόμιση του πιστοποιητικού ΕΝ.Φ.Ι.Α. στη μονομερή εξάλειψη 
υποθήκης ή στην άρση κατάσχεσης ή στην παραχώρηση υποθήκης ή προσημείωσης για εξασφάλιση δικαιωμάτων 
του Ελληνικού Δημοσίου. Σε κάθε περίπτωση θεωρείται έγκυρη η μνημόνευση, επισύναψη ή προσκόμιση του 
πιστοποιητικού ΕΝ.Φ.Ι.Α., στο οποίο το κτίσμα αποτυπώνεται με απόκλιση της επιφάνειάς του μέχρι πέντε 
(5) τετραγωνικά μέτρα και το γήπεδο ή το οικόπεδο αποτυπώνονται με απόκλιση μέχρι δύο τοις εκατό (2%) 
της επιφάνειάς τους ή παραλείπονται ή αναγράφονται εσφαλμένα στοιχεία που δεν επηρεάζουν τη φορολογική
ταυτότητα του ακινήτου και δεν συνεπάγονται την επιβολή μειωμένου φόρου.» 

[heading=paragraph]
=== {empty}

Οι τυχόν παραλείψεις ή σφάλματα ως προς τα στοιχεία του ακινήτου, που αναφέρονται στο πιστοποιητικό
του ΕΝ.Φ.Ι.Α. που προσαρτάται και μνημονεύεται σε συμβολαιογραφικές πράξεις που συντάχθηκαν μέχρι 
την έναρξη ισχύος του παρόντος νόμου δεν επιφέρουν ακυρότητα των πράξεων αυτών.

[heading=paragraph]
=== {empty}

Η παρ. 6 του άρθρου 54Α του Ν. 4174/2013 αντικαθίσταται ως ακολούθως:

«6. Οι συμβολαιογράφοι, οι φύλακες μεταγραφών και οι προϊστάμενοι των κτηματολογικών γραφείων, που 
παραβαίνουν τις υποχρεώσεις που προβλέπονται στο παρόν άρθρο, υπόκεινται σε πρόστιμο που ορίζεται σε 
ένα τοις χιλίοις (1‰) επί της αξίας του μεταβιβαζομένου ακινήτου ή δικαιώματος επ' αυτού, το οποίο πρόστιμο 
δεν μπορεί να είναι κατώτερο από 300,00 ευρώ ούτε ανώτερο από 1.000,00 ευρώ. Σε περίπτωση υποτροπής 
το πρόστιμο διπλασιάζεται.»

[heading=article,type=entry-into-force]
== Έναρξη ισχύος

[heading=paragraph]
=== {empty}

Οι διατάξεις του παρόντος ισχύουν από την ημερομηνία δημοσίευσης στην Εφημερίδα της Κυβερνήσεως.

Παραγγέλλομε τη δημοσίευση του παρόντος στην Εφημερίδα της Κυβερνήσεως και την εκτέλεσή του ως 
νόμου του Κράτους.

[.colophon]
== Υπογραφές

Αθήνα, 16 Ιουνίου 2015 +
Ο ΠΡΟΕΔΡΟΣ ΤΗΣ ΔΗΜΟΚΡΑΤΙΑΣ +
ΠΡΟΚΟΠΙΟΣ Β. ΠΑΥΛΟΠΟΥΛΟΣ